# pgpass Secret for CloudNativePG PostgreSQL
# Use with the CNPG postgres.yaml deployment
#
# Note: These passwords must match the passwords in postgres.yaml
# (registry-db-app-credentials and registry-db-migrator-credentials secrets)
---
apiVersion: v1
kind: Secret
metadata:
  name: cnpg-pgpass
  namespace: toolhive-system
type: Opaque
stringData:
  # Format: hostname:port:database:username:password
  # Uses the CNPG read-write service (registry-db-rw)
  .pgpass: |
    registry-db-rw:5432:registry:db_app:CHANGE_ME_app_password
    registry-db-rw:5432:registry:db_migrator:CHANGE_ME_migrator_password
