// Code generated by MockGen. DO NOT EDIT.
// Source: validator.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_validator.go -package=mocks -source=validator.go tokenValidatorInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	jwt "github.com/golang-jwt/jwt/v5"
	gomock "go.uber.org/mock/gomock"
)

// MocktokenValidatorInterface is a mock of tokenValidatorInterface interface.
type MocktokenValidatorInterface struct {
	ctrl     *gomock.Controller
	recorder *MocktokenValidatorInterfaceMockRecorder
	isgomock struct{}
}

// MocktokenValidatorInterfaceMockRecorder is the mock recorder for MocktokenValidatorInterface.
type MocktokenValidatorInterfaceMockRecorder struct {
	mock *MocktokenValidatorInterface
}

// NewMocktokenValidatorInterface creates a new mock instance.
func NewMocktokenValidatorInterface(ctrl *gomock.Controller) *MocktokenValidatorInterface {
	mock := &MocktokenValidatorInterface{ctrl: ctrl}
	mock.recorder = &MocktokenValidatorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktokenValidatorInterface) EXPECT() *MocktokenValidatorInterfaceMockRecorder {
	return m.recorder
}

// ValidateToken mocks base method.
func (m *MocktokenValidatorInterface) ValidateToken(ctx context.Context, token string) (jwt.MapClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, token)
	ret0, _ := ret[0].(jwt.MapClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MocktokenValidatorInterfaceMockRecorder) ValidateToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MocktokenValidatorInterface)(nil).ValidateToken), ctx, token)
}
