// Code generated by MockGen. DO NOT EDIT.
// Source: validator.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_validator.go -package=mocks -source=validator.go TokenValidatorInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	jwt "github.com/golang-jwt/jwt/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenValidatorInterface is a mock of TokenValidatorInterface interface.
type MockTokenValidatorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTokenValidatorInterfaceMockRecorder
	isgomock struct{}
}

// MockTokenValidatorInterfaceMockRecorder is the mock recorder for MockTokenValidatorInterface.
type MockTokenValidatorInterfaceMockRecorder struct {
	mock *MockTokenValidatorInterface
}

// NewMockTokenValidatorInterface creates a new mock instance.
func NewMockTokenValidatorInterface(ctrl *gomock.Controller) *MockTokenValidatorInterface {
	mock := &MockTokenValidatorInterface{ctrl: ctrl}
	mock.recorder = &MockTokenValidatorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenValidatorInterface) EXPECT() *MockTokenValidatorInterfaceMockRecorder {
	return m.recorder
}

// ValidateToken mocks base method.
func (m *MockTokenValidatorInterface) ValidateToken(ctx context.Context, token string) (jwt.MapClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", ctx, token)
	ret0, _ := ret[0].(jwt.MapClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockTokenValidatorInterfaceMockRecorder) ValidateToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockTokenValidatorInterface)(nil).ValidateToken), ctx, token)
}
