version: "2"
run:
  issues-exit-code: 1
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  default: none
  enable:
    - depguard
    - exhaustive
    - ginkgolinter
    - goconst
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - paralleltest
    - promlinter
    - revive
    - staticcheck
    - thelper
    - tparallel
    - unparam
    - unused
  settings:
    depguard:
      rules:
        prevent_unmaintained_packages:
          list-mode: lax
          files:
            - $all
            - '!$test'
          deny:
            - pkg: io/ioutil
              desc: this is deprecated
    ginkgolinter:
      # Suppress the wrong length assertion warning
      suppress-len-assertion: false
      # Suppress the wrong nil assertion warning
      suppress-nil-assertion: false
      # Suppress the wrong error assertion warning
      suppress-err-assertion: false
      # Suppress the wrong comparison assertion warning
      suppress-compare-assertion: false
      # Suppress the wrong async assertion warning
      suppress-async-assertion: false
      # Suppress warning for comparing values from different types
      suppress-type-compare-assertion: false
      # Forbid focus containers (FIt, FDescribe, etc.)
      forbid-focus-container: true
      # Force using Expect with To/ToNot instead of Should/ShouldNot
      force-expect-to: false
      # Validate async intervals (timeout vs polling)
      validate-async-intervals: true
      # Forbid spec pollution (variable initialization in container nodes)
      forbid-spec-pollution: false
      # Force using Succeed() for functions and HaveOccurred() for errors
      force-succeed: false
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G601
    lll:
      line-length: 130
    revive:
      severity: warning
      rules:
        - name: blank-imports
          severity: warning
        - name: context-as-argument
        - name: context-keys-type
        - name: duplicated-imports
        - name: error-naming
        - name: error-return
        - name: exported
          severity: error
        - name: if-return
        - name: identical-branches
        - name: indent-error-flow
        - name: import-shadowing
        - name: package-comments
        - name: redefines-builtin-id
        - name: struct-tag
        - name: unconditional-recursion
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: unused-parameter
        - name: unused-receiver
        - name: unhandled-error
          disabled: true
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
          - gocyclo
          - errcheck
          - dupl
          - gosec
        path: (.+)_test\.go
      - linters:
          - lll
        path: .golangci.yml
      # These are auto-generated, so it makes no sense including them.
      - linters:
          - dupl
          - errcheck
          - gci
          - gocyclo
          - gosec
          - lll
        path: (.*)mock_(.+)\.go
      # These are auto-generated, so it makes no sense including them.
      - linters:
          - dupl
          - errcheck
          - gci
          - gocyclo
          - gosec
          - lll
        path: (.*)zz_generated\.deepcopy\.go
      # This is auto-generated, so it makes no sense including it.
      - linters:
          - dupl
          - errcheck
          - gci
          - gocyclo
          - gosec
          - lll
        path: docs/server/docs.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/stacklok/toolhive-registry-server)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
