version: '3'

# includes:
#   registry-api:
#     taskfile: ./cmd/thv-registry-api/Taskfile.yml
#     flatten: true

tasks:
  docs:
    desc: Regenerate the registry API documentation
    cmds:
      - rm -rf docs/cli/*
      - go run cmd/help/main.go --dir docs/cli
      - swag init -g cmd/thv-registry-api/docs.go --v3.1 -o docs/thv-registry-api

  install-swagger:
    desc: Install the swag tool for OpenAPI/Swagger generation
    cmds:
      - go install github.com/swaggo/swag/v2/cmd/swag@latest

  install-mock:
    desc: Install the mockgen tool for mock generation
    cmds:
      - go install go.uber.org/mock/mockgen@latest

  install-gotestfmt:
    desc: Install the gotestfmt tool for test output formatting
    cmds:
      - go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest

  install-golangci-lint:
    desc: Install the golangci-lint tool for linting
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  install-ko:
    desc: Install the ko tool for building container images
    cmds:
      - go install github.com/google/ko@latest

  install-dev-deps:
    desc: Install the development dependencies
    deps:
      - install-gotestfmt
      - install-mock
      - install-swagger
      - install-golangci-lint
      - install-ko

  gen:
    desc: Generate mock files using go generate
    deps: [install-mock]
    cmds:
      - go generate ./...

  lint:
    desc: Run linting tools
    deps: [gen, install-golangci-lint]
    cmds:
      - golangci-lint run ./...
      - go vet ./...

  lint-fix:
    desc: Run linting tools, and apply fixes.
    deps: [install-golangci-lint]
    cmds:
      - golangci-lint run --fix ./...

  build:
    desc: Build the registry API binary
    cmds:
      - go build -o bin/thv-registry-api ./cmd/thv-registry-api

  build-image:
    desc: Build the registry API image with ko
    deps: [install-ko]
    env:
      KO_DOCKER_REPO: ghcr.io/stacklok/toolhive-registry-server
    cmds:
      - ko build --local -B ./cmd/thv-registry-api

  test:
    desc: Run registry API tests
    deps: [install-gotestfmt]
    cmds:
      # We have to use ldflags to avoid the LC_DYSYMTAB linker warning.
      - go test -ldflags=-extldflags=-Wl,-w -race -json $(go list ./... | grep -v '/test-integration') | gotestfmt -hide "all"

  setup-integration-deps:
    desc: Setup dependencies for integration tests
    cmds:
      - go install sigs.k8s.io/controller-runtime/tools/setup-envtest@release-0.22
      - go install github.com/onsi/ginkgo/v2/ginkgo@latest

  test-integration:
    desc: Run integration tests
    deps: [setup-integration-deps]
    cmds:
      - KUBEBUILDER_ASSETS="$($(go env GOPATH)/bin/setup-envtest use 1.31.0 -p path)" $(go env GOPATH)/bin/ginkgo -v -p ./test-integration/...

  test-coverage:
    desc: Run registry API tests with coverage
    deps: [install-gotestfmt]
    cmds:
      # We have to use ldflags to avoid the LC_DYSYMTAB linker warning.
      - go test -ldflags=-extldflags=-Wl,-w -race -json -coverprofile=coverage.out $(go list ./... | grep -v '/test-integration') | gotestfmt -hide "all"
      - go tool cover -func=coverage.out
      - echo "Generating HTML coverage report in coverage.html"
      - go tool cover -html=coverage.out -o coverage.html

  all:
    desc: Run linting, tests, and build
    deps: [lint, test-coverage, build]
