version: '3'

vars:
  CONTAINER_RUNTIME:
    sh: |
      if command -v podman >/dev/null 2>&1; then
        echo "podman"
      else
        echo "docker"
      fi
  REPO: '{{.REPO | default "ghcr.io/stacklok/toolhive-registry-server"}}'

tasks:
  docs:
    desc: Regenerate the registry API documentation
    vars:
      SWAG_OUTPUT_DIR: '{{.SWAG_OUTPUT_DIR | default "docs/thv-registry-api"}}'
    cmds:
      - rm -rf docs/cli/*
      - go run cmd/help/main.go --dir docs/cli
      # NOTE: check out .swaggo file in the root of the project
      # NOTE: We suppress the output to avoid "go/build" messages, it might
      #       drop messages we care about.
      - |
        swag init -q -g cmd/thv-registry-api/docs.go \
          --v3.1 --output {{.SWAG_OUTPUT_DIR}} \
          --parseDependencyLevel 1 2>/dev/null

  install-sqlc:
    desc: Install the sqlc tool for generating database code
    cmds:
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

  install-swagger:
    desc: Install the swag tool for OpenAPI/Swagger generation
    cmds:
      - go install github.com/swaggo/swag/v2/cmd/swag@latest

  install-mock:
    desc: Install the mockgen tool for mock generation
    status:
      - which mockgen
    cmds:
      - go install go.uber.org/mock/mockgen@latest

  install-gotestfmt:
    desc: Install the gotestfmt tool for test output formatting
    cmds:
      - go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest

  install-golangci-lint:
    desc: Install the golangci-lint tool for linting
    status:
      - which golangci-lint
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

  install-deadcode:
    desc: Install the deadcode tool for checking for unused code
    cmds:
      - go install golang.org/x/tools/cmd/deadcode@latest

  install-ko:
    desc: Install the ko tool for building container images
    cmds:
      - go install github.com/google/ko@latest

  install-dev-deps:
    desc: Install the development dependencies
    deps:
      - install-gotestfmt
      - install-mock
      - install-swagger
      - install-golangci-lint
      - install-deadcode
      - install-ko
      - install-sqlc

  gen:
    desc: Run code generation tasks
    deps:
      - task: install-mock
        silent: true
      - task: install-sqlc
        silent: true
    cmds:
      - go generate ./...
      - sqlc generate

  deadcode:
    desc: Run deadcode tool for checking for unused code
    deps:
      - task: install-deadcode
        silent: true
    cmds:
      - cmd: |
          if test -z "$(deadcode -test ./...)"; then
            echo "✅ No unused code found"
          else
            echo "❌ Unused code found"
            exit 1
          fi
        silent: true

  lint:
    desc: Run linting tools
    deps:
      - task: gen
        silent: true
      - task: install-golangci-lint
        silent: true
      - task: install-deadcode
        silent: true
    cmds:
      - golangci-lint run ./...
      - go vet ./...

  lint-fix:
    desc: Run linting tools, and apply fixes.
    deps:
      - task: install-golangci-lint
        silent: true
    cmds:
      - golangci-lint run --fix ./...

  build:
    desc: Build the registry API binary
    cmds:
      - go build -o bin/thv-registry-api ./cmd/thv-registry-api

  build-image:
    desc: Build the registry API image with ko
    deps:
      - task: install-ko
        silent: true
    env:
      KO_DOCKER_REPO: '{{.REPO}}'
    cmds:
      - ko build --local -B ./cmd/thv-registry-api

  build-image-ubi:
    desc: Build the registry API image with UBI base image
    vars:
      COMMIT:
        sh: git rev-parse --short HEAD || echo "unknown"
      BUILD_DATE: '{{dateInZone "2006-01-02T15:04:05Z" (now) "UTC"}}'
      SHA:
        sh: git rev-parse HEAD || echo "unknown"
    cmds:
      - |
        {{.CONTAINER_RUNTIME}} build --load \
        -t {{.REPO}}:{{.SHA}}-ubi \
        --build-arg VERSION={{.SHA}}-ubi \
        --build-arg COMMIT={{.COMMIT}} \
        --build-arg BUILD_DATE={{.BUILD_DATE}} \
        --label name="toolhive-registry-api" \
        --label vendor="Stacklok" \
        --label maintainer="Stacklok" .

  test:
    desc: Run registry API tests
    deps: 
      - task: install-gotestfmt
        silent: true
    cmds:
      # We have to use ldflags to avoid the LC_DYSYMTAB linker warning.
      - go test -ldflags=-extldflags=-Wl,-w -race -json ./... | gotestfmt -hide "all"

  test-coverage:
    desc: Run registry API tests with coverage
    deps:
      - task: install-gotestfmt
        silent: true
    cmds:
      # We have to use ldflags to avoid the LC_DYSYMTAB linker warning.
      - go test -ldflags=-extldflags=-Wl,-w -race -json -coverprofile=coverage.out ./... | gotestfmt -hide "all"
      - go tool cover -func=coverage.out
      - echo "Generating HTML coverage report in coverage.html"
      - go tool cover -html=coverage.out -o coverage.html

  all:
    desc: Run linting, tests, and build
    deps: [lint, test-coverage, build]
