// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: definitions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/stacklok/toolhive-registry-server/internal/db/pgtypes"
)

const defBlockedSources = `-- name: DefBlockedSources :one
SELECT EXISTS(SELECT 1 FROM source s WHERE s.creation_type='CONFIG' AND NOT (s.name=ANY($1::text[]))
AND (s.claims IS NOT NULL OR EXISTS(SELECT 1 FROM registry_entry e WHERE e.source_id=s.id AND e.claims IS NOT NULL)))
`

func (q *Queries) DefBlockedSources(ctx context.Context, dollar_1 []string) (bool, error) {
	row := q.db.QueryRow(ctx, defBlockedSources, dollar_1)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const defBlockedViews = `-- name: DefBlockedViews :one
SELECT EXISTS(SELECT 1 FROM registry WHERE creation_type='CONFIG' AND NOT (name=ANY($1::text[])) AND claims IS NOT NULL)
`

func (q *Queries) DefBlockedViews(ctx context.Context, dollar_1 []string) (bool, error) {
	row := q.db.QueryRow(ctx, defBlockedViews, dollar_1)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const defDeleteAPISource = `-- name: DefDeleteAPISource :exec
DELETE FROM source WHERE id=$1::uuid AND creation_type='API'
`

func (q *Queries) DefDeleteAPISource(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.Exec(ctx, defDeleteAPISource, dollar_1)
	return err
}

const defDeleteAPIView = `-- name: DefDeleteAPIView :exec
DELETE FROM registry WHERE name=$1 AND creation_type='API'
`

func (q *Queries) DefDeleteAPIView(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, defDeleteAPIView, name)
	return err
}

const defDeleteConfigLinks = `-- name: DefDeleteConfigLinks :exec
DELETE FROM registry_source WHERE registry_id IN (SELECT id FROM registry WHERE creation_type='CONFIG')
`

func (q *Queries) DefDeleteConfigLinks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, defDeleteConfigLinks)
	return err
}

const defDeleteViewLinks = `-- name: DefDeleteViewLinks :exec
DELETE FROM registry_source WHERE registry_id=$1::uuid
`

func (q *Queries) DefDeleteViewLinks(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.Exec(ctx, defDeleteViewLinks, dollar_1)
	return err
}

const defGetSource = `-- name: DefGetSource :one
SELECT id::text AS id, name, creation_type::text AS origin, source_type, source_config, filter_config,
 COALESCE((extract(epoch from sync_schedule)*1000000)::bigint,0) AS micros
FROM source WHERE name=$1
`

type DefGetSourceRow struct {
	ID           string      `json:"id"`
	Name         string      `json:"name"`
	Origin       string      `json:"origin"`
	SourceType   string      `json:"source_type"`
	SourceConfig []byte      `json:"source_config"`
	FilterConfig []byte      `json:"filter_config"`
	Micros       interface{} `json:"micros"`
}

func (q *Queries) DefGetSource(ctx context.Context, name string) (DefGetSourceRow, error) {
	row := q.db.QueryRow(ctx, defGetSource, name)
	var i DefGetSourceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Origin,
		&i.SourceType,
		&i.SourceConfig,
		&i.FilterConfig,
		&i.Micros,
	)
	return i, err
}

const defGetView = `-- name: DefGetView :one
SELECT name, creation_type::text AS origin FROM registry WHERE name=$1
`

type DefGetViewRow struct {
	Name   string `json:"name"`
	Origin string `json:"origin"`
}

func (q *Queries) DefGetView(ctx context.Context, name string) (DefGetViewRow, error) {
	row := q.db.QueryRow(ctx, defGetView, name)
	var i DefGetViewRow
	err := row.Scan(&i.Name, &i.Origin)
	return i, err
}

const defInsertAPIView = `-- name: DefInsertAPIView :one
INSERT INTO registry(name,creation_type) VALUES($1,'API') RETURNING id::text
`

func (q *Queries) DefInsertAPIView(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRow(ctx, defInsertAPIView, name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const defInsertSource = `-- name: DefInsertSource :one
INSERT INTO source(name,creation_type,source_type,source_config,filter_config,sync_schedule,syncable)
VALUES($1,'API',$2,$3::jsonb,$4::jsonb,$5::interval,$6) RETURNING id::text
`

type DefInsertSourceParams struct {
	Name       string           `json:"name"`
	SourceType string           `json:"source_type"`
	Column3    []byte           `json:"column_3"`
	Column4    []byte           `json:"column_4"`
	Column5    pgtypes.Interval `json:"column_5"`
	Syncable   bool             `json:"syncable"`
}

func (q *Queries) DefInsertSource(ctx context.Context, arg DefInsertSourceParams) (string, error) {
	row := q.db.QueryRow(ctx, defInsertSource,
		arg.Name,
		arg.SourceType,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Syncable,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const defLink = `-- name: DefLink :execrows
INSERT INTO registry_source(registry_id,source_id,position)
SELECT $1::uuid,id,$3::int FROM source WHERE name=$2
`

type DefLinkParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Name    string    `json:"name"`
	Column3 int32     `json:"column_3"`
}

func (q *Queries) DefLink(ctx context.Context, arg DefLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, defLink, arg.Column1, arg.Name, arg.Column3)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const defListSources = `-- name: DefListSources :many
SELECT id::text AS id, name, creation_type::text AS origin, source_type, source_config, filter_config,
 COALESCE((extract(epoch from sync_schedule)*1000000)::bigint,0) AS micros
FROM source ORDER BY name COLLATE "C"
`

type DefListSourcesRow struct {
	ID           string      `json:"id"`
	Name         string      `json:"name"`
	Origin       string      `json:"origin"`
	SourceType   string      `json:"source_type"`
	SourceConfig []byte      `json:"source_config"`
	FilterConfig []byte      `json:"filter_config"`
	Micros       interface{} `json:"micros"`
}

func (q *Queries) DefListSources(ctx context.Context) ([]DefListSourcesRow, error) {
	rows, err := q.db.Query(ctx, defListSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DefListSourcesRow{}
	for rows.Next() {
		var i DefListSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Origin,
			&i.SourceType,
			&i.SourceConfig,
			&i.FilterConfig,
			&i.Micros,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const defListViewNames = `-- name: DefListViewNames :many
SELECT name FROM registry ORDER BY name COLLATE "C"
`

func (q *Queries) DefListViewNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, defListViewNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const defLockSource = `-- name: DefLockSource :one
SELECT id::text AS id, name, creation_type::text AS origin, source_type, source_config, filter_config,
 COALESCE((extract(epoch from sync_schedule)*1000000)::bigint,0) AS micros
FROM source WHERE name=$1 FOR UPDATE
`

type DefLockSourceRow struct {
	ID           string      `json:"id"`
	Name         string      `json:"name"`
	Origin       string      `json:"origin"`
	SourceType   string      `json:"source_type"`
	SourceConfig []byte      `json:"source_config"`
	FilterConfig []byte      `json:"filter_config"`
	Micros       interface{} `json:"micros"`
}

func (q *Queries) DefLockSource(ctx context.Context, name string) (DefLockSourceRow, error) {
	row := q.db.QueryRow(ctx, defLockSource, name)
	var i DefLockSourceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Origin,
		&i.SourceType,
		&i.SourceConfig,
		&i.FilterConfig,
		&i.Micros,
	)
	return i, err
}

const defLockView = `-- name: DefLockView :one
SELECT name, creation_type::text AS origin FROM registry WHERE name=$1 FOR UPDATE
`

type DefLockViewRow struct {
	Name   string `json:"name"`
	Origin string `json:"origin"`
}

func (q *Queries) DefLockView(ctx context.Context, name string) (DefLockViewRow, error) {
	row := q.db.QueryRow(ctx, defLockView, name)
	var i DefLockViewRow
	err := row.Scan(&i.Name, &i.Origin)
	return i, err
}

const defPruneSources = `-- name: DefPruneSources :exec
DELETE FROM source WHERE creation_type='CONFIG' AND NOT (name=ANY($1::text[])) AND claims IS NULL
`

func (q *Queries) DefPruneSources(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, defPruneSources, dollar_1)
	return err
}

const defPruneViews = `-- name: DefPruneViews :exec
DELETE FROM registry WHERE creation_type='CONFIG' AND NOT (name=ANY($1::text[])) AND claims IS NULL
`

func (q *Queries) DefPruneViews(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, defPruneViews, dollar_1)
	return err
}

const defSourceClaims = `-- name: DefSourceClaims :one
SELECT (claims IS NOT NULL)::boolean AS has_claims FROM source WHERE name=$1
`

func (q *Queries) DefSourceClaims(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, defSourceClaims, name)
	var has_claims bool
	err := row.Scan(&has_claims)
	return has_claims, err
}

const defSourceRaw = `-- name: DefSourceRaw :one
SELECT source_config, filter_config FROM source WHERE name=$1
`

type DefSourceRawRow struct {
	SourceConfig []byte `json:"source_config"`
	FilterConfig []byte `json:"filter_config"`
}

func (q *Queries) DefSourceRaw(ctx context.Context, name string) (DefSourceRawRow, error) {
	row := q.db.QueryRow(ctx, defSourceRaw, name)
	var i DefSourceRawRow
	err := row.Scan(&i.SourceConfig, &i.FilterConfig)
	return i, err
}

const defSourceUsed = `-- name: DefSourceUsed :one
SELECT EXISTS(SELECT 1 FROM registry_source WHERE source_id=$1::uuid)
`

func (q *Queries) DefSourceUsed(ctx context.Context, dollar_1 uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, defSourceUsed, dollar_1)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const defTouchAPIView = `-- name: DefTouchAPIView :exec
UPDATE registry SET updated_at=now() WHERE id=$1::uuid AND creation_type='API'
`

func (q *Queries) DefTouchAPIView(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.Exec(ctx, defTouchAPIView, dollar_1)
	return err
}

const defUpdateSource = `-- name: DefUpdateSource :exec
UPDATE source SET source_config=$2::jsonb,filter_config=$3::jsonb,sync_schedule=$4::interval,syncable=$5,updated_at=now()
WHERE name=$1 AND creation_type='API'
`

type DefUpdateSourceParams struct {
	Name     string           `json:"name"`
	Column2  []byte           `json:"column_2"`
	Column3  []byte           `json:"column_3"`
	Column4  pgtypes.Interval `json:"column_4"`
	Syncable bool             `json:"syncable"`
}

func (q *Queries) DefUpdateSource(ctx context.Context, arg DefUpdateSourceParams) error {
	_, err := q.db.Exec(ctx, defUpdateSource,
		arg.Name,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Syncable,
	)
	return err
}

const defUpsertConfigSource = `-- name: DefUpsertConfigSource :execrows
INSERT INTO source(name,creation_type,source_type,source_config,filter_config,sync_schedule,syncable)
VALUES($1,'CONFIG',$2,$3::jsonb,$4::jsonb,$5::interval,$6)
ON CONFLICT(name) DO UPDATE SET source_config=excluded.source_config,filter_config=excluded.filter_config,
sync_schedule=excluded.sync_schedule,syncable=excluded.syncable,updated_at=now()
WHERE source.creation_type='CONFIG' AND source.source_type=excluded.source_type AND source.claims IS NULL
`

type DefUpsertConfigSourceParams struct {
	Name       string           `json:"name"`
	SourceType string           `json:"source_type"`
	Column3    []byte           `json:"column_3"`
	Column4    []byte           `json:"column_4"`
	Column5    pgtypes.Interval `json:"column_5"`
	Syncable   bool             `json:"syncable"`
}

func (q *Queries) DefUpsertConfigSource(ctx context.Context, arg DefUpsertConfigSourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, defUpsertConfigSource,
		arg.Name,
		arg.SourceType,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Syncable,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const defUpsertConfigView = `-- name: DefUpsertConfigView :one
INSERT INTO registry(name,creation_type) VALUES($1,'CONFIG')
ON CONFLICT(name) DO UPDATE SET updated_at=now()
WHERE registry.creation_type='CONFIG' AND registry.claims IS NULL
RETURNING id::text
`

func (q *Queries) DefUpsertConfigView(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRow(ctx, defUpsertConfigView, name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const defViewClaims = `-- name: DefViewClaims :one
SELECT (claims IS NOT NULL)::boolean AS has_claims FROM registry WHERE name=$1
`

func (q *Queries) DefViewClaims(ctx context.Context, name string) (bool, error) {
	row := q.db.QueryRow(ctx, defViewClaims, name)
	var has_claims bool
	err := row.Scan(&has_claims)
	return has_claims, err
}

const defViewID = `-- name: DefViewID :one
SELECT id::text FROM registry WHERE name=$1
`

func (q *Queries) DefViewID(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRow(ctx, defViewID, name)
	var id string
	err := row.Scan(&id)
	return id, err
}

const defViewSources = `-- name: DefViewSources :many
SELECT s.name FROM registry_source rs JOIN registry r ON r.id=rs.registry_id JOIN source s ON s.id=rs.source_id
WHERE r.name=$1 ORDER BY rs.position,s.name COLLATE "C"
`

func (q *Queries) DefViewSources(ctx context.Context, name string) ([]string, error) {
	rows, err := q.db.Query(ctx, defViewSources, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
