// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entry_catalog.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const entryDeleteEmptyNames = `-- name: EntryDeleteEmptyNames :exec
DELETE FROM registry_entry e WHERE e.source_id=$1::uuid
AND NOT EXISTS (SELECT 1 FROM entry_version v WHERE v.entry_id=e.id)
`

func (q *Queries) EntryDeleteEmptyNames(ctx context.Context, sourceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, entryDeleteEmptyNames, sourceID)
	return err
}

const entryDeleteVersion = `-- name: EntryDeleteVersion :execrows
DELETE FROM entry_version v WHERE v.id IN (
 SELECT v.id FROM registry_entry e JOIN entry_version v ON v.entry_id=e.id
 WHERE e.source_id=$1::uuid AND e.entry_type=$2
 AND e.name=$3 AND v.version=$4)
`

type EntryDeleteVersionParams struct {
	SourceID  uuid.UUID `json:"source_id"`
	EntryType EntryType `json:"entry_type"`
	Name      string    `json:"name"`
	Version   string    `json:"version"`
}

func (q *Queries) EntryDeleteVersion(ctx context.Context, arg EntryDeleteVersionParams) (int64, error) {
	result, err := q.db.Exec(ctx, entryDeleteVersion,
		arg.SourceID,
		arg.EntryType,
		arg.Name,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const entryDropLatest = `-- name: EntryDropLatest :exec
DELETE FROM latest_entry_version WHERE source_id=$1::uuid
AND entry_type=$2 AND name=$3
`

type EntryDropLatestParams struct {
	SourceID  uuid.UUID `json:"source_id"`
	EntryType EntryType `json:"entry_type"`
	Name      string    `json:"name"`
}

func (q *Queries) EntryDropLatest(ctx context.Context, arg EntryDropLatestParams) error {
	_, err := q.db.Exec(ctx, entryDropLatest, arg.SourceID, arg.EntryType, arg.Name)
	return err
}

const entryHasClaims = `-- name: EntryHasClaims :one
SELECT EXISTS(SELECT 1 FROM registry_entry WHERE source_id=$1::uuid AND claims IS NOT NULL)
`

func (q *Queries) EntryHasClaims(ctx context.Context, sourceID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, entryHasClaims, sourceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const entryList = `-- name: EntryList :many
SELECT v.id::text AS id, e.name, v.version, v.title, v.description,
 v.created_at, v.updated_at, coalesce(l.latest_version_id = v.id, false)::boolean AS is_latest,
 to_jsonb(s) AS server_data, to_jsonb(sk) AS skill_data, to_jsonb(pl) AS plugin_data,
 (SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY p.pkg_identifier,p.transport), '[]'::jsonb)
    FROM mcp_server_package p WHERE p.server_id=v.id)::text AS server_packages,
 (SELECT coalesce(jsonb_agg(to_jsonb(r) ORDER BY r.transport,r.transport_url), '[]'::jsonb)
    FROM mcp_server_remote r WHERE r.server_id=v.id)::text AS server_remotes,
 (SELECT coalesce(jsonb_agg(to_jsonb(i) ORDER BY i.source_uri), '[]'::jsonb)
    FROM mcp_server_icon i WHERE i.server_id=v.id)::text AS server_icons,
 (SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY p.identifier), '[]'::jsonb)
    FROM skill_oci_package p WHERE p.skill_id=v.id)::text AS skill_oci,
 (SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY p.url), '[]'::jsonb)
    FROM skill_git_package p WHERE p.skill_id=v.id)::text AS skill_git,
 (SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY p.identifier), '[]'::jsonb)
    FROM plugin_oci_package p WHERE p.plugin_id=v.id)::text AS plugin_oci,
 (SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY p.url), '[]'::jsonb)
    FROM plugin_git_package p WHERE p.plugin_id=v.id)::text AS plugin_git
FROM registry_entry e JOIN entry_version v ON v.entry_id=e.id
LEFT JOIN latest_entry_version l ON l.source_id=e.source_id AND l.entry_type=e.entry_type AND l.name=e.name
LEFT JOIN mcp_server s ON s.version_id=v.id
LEFT JOIN skill sk ON sk.version_id=v.id
LEFT JOIN plugin pl ON pl.version_id=v.id
WHERE e.source_id=$1::uuid AND e.entry_type=$2
AND ($3::text IS NULL OR e.name=$3::text)
AND ($4::text IS NULL OR v.version=$4::text)
AND (NOT $5::boolean OR l.latest_version_id=v.id)
AND ($6::text IS NULL OR strpos(lower(e.name),lower($6::text))>0
 OR strpos(lower(coalesce(v.title,'')),lower($6::text))>0
 OR strpos(lower(coalesce(v.description,'')),lower($6::text))>0)
AND ($7::text IS NULL OR
 (e.name COLLATE "C",v.version COLLATE "C") >
 ($7::text COLLATE "C",$8::text COLLATE "C"))
ORDER BY e.name COLLATE "C",v.version COLLATE "C"
LIMIT $9::bigint
`

type EntryListParams struct {
	SourceID      uuid.UUID `json:"source_id"`
	EntryType     EntryType `json:"entry_type"`
	Name          *string   `json:"name"`
	Version       *string   `json:"version"`
	LatestOnly    bool      `json:"latest_only"`
	Search        *string   `json:"search"`
	CursorName    *string   `json:"cursor_name"`
	CursorVersion *string   `json:"cursor_version"`
	PageSize      int64     `json:"page_size"`
}

type EntryListRow struct {
	ID             string     `json:"id"`
	Name           string     `json:"name"`
	Version        string     `json:"version"`
	Title          *string    `json:"title"`
	Description    *string    `json:"description"`
	CreatedAt      *time.Time `json:"created_at"`
	UpdatedAt      *time.Time `json:"updated_at"`
	IsLatest       bool       `json:"is_latest"`
	ServerData     []byte     `json:"server_data"`
	SkillData      []byte     `json:"skill_data"`
	PluginData     []byte     `json:"plugin_data"`
	ServerPackages string     `json:"server_packages"`
	ServerRemotes  string     `json:"server_remotes"`
	ServerIcons    string     `json:"server_icons"`
	SkillOci       string     `json:"skill_oci"`
	SkillGit       string     `json:"skill_git"`
	PluginOci      string     `json:"plugin_oci"`
	PluginGit      string     `json:"plugin_git"`
}

func (q *Queries) EntryList(ctx context.Context, arg EntryListParams) ([]EntryListRow, error) {
	rows, err := q.db.Query(ctx, entryList,
		arg.SourceID,
		arg.EntryType,
		arg.Name,
		arg.Version,
		arg.LatestOnly,
		arg.Search,
		arg.CursorName,
		arg.CursorVersion,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntryListRow{}
	for rows.Next() {
		var i EntryListRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Version,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsLatest,
			&i.ServerData,
			&i.SkillData,
			&i.PluginData,
			&i.ServerPackages,
			&i.ServerRemotes,
			&i.ServerIcons,
			&i.SkillOci,
			&i.SkillGit,
			&i.PluginOci,
			&i.PluginGit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const entryManagedSource = `-- name: EntryManagedSource :one
SELECT id FROM source WHERE source_type='managed' FOR UPDATE
`

func (q *Queries) EntryManagedSource(ctx context.Context) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, entryManagedSource)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const entrySource = `-- name: EntrySource :one
SELECT id, name, source_type, (claims IS NOT NULL)::boolean AS has_claims
FROM source WHERE id=$1::uuid FOR UPDATE
`

type EntrySourceRow struct {
	ID         uuid.UUID `json:"id"`
	Name       string    `json:"name"`
	SourceType string    `json:"source_type"`
	HasClaims  bool      `json:"has_claims"`
}

func (q *Queries) EntrySource(ctx context.Context, sourceID uuid.UUID) (EntrySourceRow, error) {
	row := q.db.QueryRow(ctx, entrySource, sourceID)
	var i EntrySourceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SourceType,
		&i.HasClaims,
	)
	return i, err
}

const entrySourceExists = `-- name: EntrySourceExists :one
SELECT EXISTS(SELECT 1 FROM source WHERE id=$1::uuid)
`

func (q *Queries) EntrySourceExists(ctx context.Context, sourceID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, entrySourceExists, sourceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const entryVersionExists = `-- name: EntryVersionExists :one
SELECT EXISTS(SELECT 1 FROM registry_entry e JOIN entry_version v ON v.entry_id=e.id
WHERE e.source_id=$1::uuid AND e.entry_type=$2
AND e.name=$3 AND v.version=$4)
`

type EntryVersionExistsParams struct {
	SourceID  uuid.UUID `json:"source_id"`
	EntryType EntryType `json:"entry_type"`
	Name      string    `json:"name"`
	Version   string    `json:"version"`
}

func (q *Queries) EntryVersionExists(ctx context.Context, arg EntryVersionExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, entryVersionExists,
		arg.SourceID,
		arg.EntryType,
		arg.Name,
		arg.Version,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const entryVersionsForName = `-- name: EntryVersionsForName :many
SELECT v.id, v.version FROM registry_entry e JOIN entry_version v ON v.entry_id=e.id
WHERE e.source_id=$1::uuid AND e.entry_type=$2 AND e.name=$3
`

type EntryVersionsForNameParams struct {
	SourceID  uuid.UUID `json:"source_id"`
	EntryType EntryType `json:"entry_type"`
	Name      string    `json:"name"`
}

type EntryVersionsForNameRow struct {
	ID      uuid.UUID `json:"id"`
	Version string    `json:"version"`
}

func (q *Queries) EntryVersionsForName(ctx context.Context, arg EntryVersionsForNameParams) ([]EntryVersionsForNameRow, error) {
	rows, err := q.db.Query(ctx, entryVersionsForName, arg.SourceID, arg.EntryType, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EntryVersionsForNameRow{}
	for rows.Next() {
		var i EntryVersionsForNameRow
		if err := rows.Scan(&i.ID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
