// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const jobAcquire = `-- name: JobAcquire :one
INSERT INTO registry_sync(source_id,sync_status,error_msg,started_at,ended_at,attempt_count,
 lease_id,lease_expires_at,lease_generation,observed_generation)
VALUES($1::uuid,'IN_PROGRESS',NULL,clock_timestamp(),NULL,1,gen_random_uuid(),
 clock_timestamp()+($3::bigint * interval '1 microsecond'),$2::bigint,$2::bigint)
ON CONFLICT(source_id) DO UPDATE SET
 sync_status='IN_PROGRESS',error_msg=NULL,started_at=clock_timestamp(),ended_at=NULL,
 attempt_count=registry_sync.attempt_count+1,
 lease_id=gen_random_uuid(),lease_expires_at=clock_timestamp()+($3::bigint * interval '1 microsecond'),
 lease_generation=$2::bigint,observed_generation=$2::bigint
WHERE registry_sync.lease_id IS NULL OR registry_sync.lease_expires_at <= clock_timestamp()
 OR registry_sync.lease_generation <> $2::bigint
RETURNING lease_id, lease_expires_at
`

type JobAcquireParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Column2 int64     `json:"column_2"`
	Column3 int64     `json:"column_3"`
}

type JobAcquireRow struct {
	LeaseID        *uuid.UUID         `json:"lease_id"`
	LeaseExpiresAt pgtype.Timestamptz `json:"lease_expires_at"`
}

func (q *Queries) JobAcquire(ctx context.Context, arg JobAcquireParams) (JobAcquireRow, error) {
	row := q.db.QueryRow(ctx, jobAcquire, arg.Column1, arg.Column2, arg.Column3)
	var i JobAcquireRow
	err := row.Scan(&i.LeaseID, &i.LeaseExpiresAt)
	return i, err
}

const jobClearSnapshotBaseline = `-- name: JobClearSnapshotBaseline :exec
UPDATE registry_sync SET applied_generation=NULL,last_sync_hash=NULL,last_applied_filter_hash=NULL,
 server_count=0,skill_count=0,plugin_count=0 WHERE source_id=$1::uuid
`

func (q *Queries) JobClearSnapshotBaseline(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.Exec(ctx, jobClearSnapshotBaseline, dollar_1)
	return err
}

const jobFail = `-- name: JobFail :execrows
UPDATE registry_sync SET sync_status='FAILED',error_msg=$4,ended_at=clock_timestamp(),
 lease_id=NULL,lease_expires_at=NULL,lease_generation=NULL
WHERE source_id=$1::uuid AND lease_id=$2::uuid AND lease_generation=$3::bigint
 AND lease_expires_at>clock_timestamp() AND sync_status='IN_PROGRESS'
 AND lease_generation=(SELECT definition_generation FROM source WHERE id=$1::uuid)
`

type JobFailParams struct {
	Column1  uuid.UUID `json:"column_1"`
	Column2  uuid.UUID `json:"column_2"`
	Column3  int64     `json:"column_3"`
	ErrorMsg *string   `json:"error_msg"`
}

func (q *Queries) JobFail(ctx context.Context, arg JobFailParams) (int64, error) {
	result, err := q.db.Exec(ctx, jobFail,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.ErrorMsg,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const jobFence = `-- name: JobFence :one
SELECT rs.source_id FROM registry_sync rs JOIN source s ON s.id=rs.source_id
WHERE rs.source_id=$1::uuid AND rs.lease_id=$2::uuid AND rs.lease_generation=$3::bigint
 AND rs.sync_status='IN_PROGRESS' AND rs.lease_expires_at>clock_timestamp()
 AND s.definition_generation=$3::bigint AND s.source_type <> 'managed'
FOR UPDATE OF s,rs
`

type JobFenceParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Column2 uuid.UUID `json:"column_2"`
	Column3 int64     `json:"column_3"`
}

func (q *Queries) JobFence(ctx context.Context, arg JobFenceParams) (*uuid.UUID, error) {
	row := q.db.QueryRow(ctx, jobFence, arg.Column1, arg.Column2, arg.Column3)
	var source_id *uuid.UUID
	err := row.Scan(&source_id)
	return source_id, err
}

const jobFinish = `-- name: JobFinish :execrows
UPDATE registry_sync SET sync_status='COMPLETED',error_msg=NULL,ended_at=clock_timestamp(),
 lease_id=NULL,lease_expires_at=NULL,lease_generation=NULL,
 last_sync_hash=$4,last_applied_filter_hash=$5,server_count=$6,skill_count=$7,plugin_count=$8,
 applied_generation=$3::bigint
WHERE source_id=$1::uuid AND lease_id=$2::uuid AND lease_generation=$3::bigint
 AND lease_expires_at>clock_timestamp() AND sync_status='IN_PROGRESS'
 AND lease_generation=(SELECT definition_generation FROM source WHERE id=$1::uuid)
`

type JobFinishParams struct {
	Column1               uuid.UUID `json:"column_1"`
	Column2               uuid.UUID `json:"column_2"`
	Column3               int64     `json:"column_3"`
	LastSyncHash          *string   `json:"last_sync_hash"`
	LastAppliedFilterHash *string   `json:"last_applied_filter_hash"`
	ServerCount           int64     `json:"server_count"`
	SkillCount            int64     `json:"skill_count"`
	PluginCount           int64     `json:"plugin_count"`
}

func (q *Queries) JobFinish(ctx context.Context, arg JobFinishParams) (int64, error) {
	result, err := q.db.Exec(ctx, jobFinish,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.LastSyncHash,
		arg.LastAppliedFilterHash,
		arg.ServerCount,
		arg.SkillCount,
		arg.PluginCount,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const jobFinishUnchanged = `-- name: JobFinishUnchanged :execrows
UPDATE registry_sync SET sync_status='COMPLETED',error_msg=NULL,ended_at=clock_timestamp(),
 lease_id=NULL,lease_expires_at=NULL,lease_generation=NULL
WHERE source_id=$1::uuid AND lease_id=$2::uuid AND lease_generation=$3::bigint
 AND lease_expires_at>clock_timestamp() AND sync_status='IN_PROGRESS'
 AND lease_generation=(SELECT definition_generation FROM source WHERE id=$1::uuid)
 AND applied_generation=$3::bigint AND last_sync_hash=$4::text
 AND last_applied_filter_hash=$5::text
`

type JobFinishUnchangedParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Column2 uuid.UUID `json:"column_2"`
	Column3 int64     `json:"column_3"`
	Column4 string    `json:"column_4"`
	Column5 string    `json:"column_5"`
}

func (q *Queries) JobFinishUnchanged(ctx context.Context, arg JobFinishUnchangedParams) (int64, error) {
	result, err := q.db.Exec(ctx, jobFinishUnchanged,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const jobInvalidateSnapshot = `-- name: JobInvalidateSnapshot :exec
UPDATE source SET definition_generation=definition_generation+1 WHERE id=$1::uuid
`

func (q *Queries) JobInvalidateSnapshot(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.Exec(ctx, jobInvalidateSnapshot, dollar_1)
	return err
}

const jobLockSource = `-- name: JobLockSource :one
SELECT id, definition_generation FROM source WHERE name=$1 FOR UPDATE
`

type JobLockSourceRow struct {
	ID                   uuid.UUID `json:"id"`
	DefinitionGeneration int64     `json:"definition_generation"`
}

func (q *Queries) JobLockSource(ctx context.Context, name string) (JobLockSourceRow, error) {
	row := q.db.QueryRow(ctx, jobLockSource, name)
	var i JobLockSourceRow
	err := row.Scan(&i.ID, &i.DefinitionGeneration)
	return i, err
}

const jobNext = `-- name: JobNext :one
SELECT s.name FROM source s LEFT JOIN registry_sync rs ON rs.source_id=s.id
WHERE s.syncable AND s.source_type IN ('git','api','file') AND s.sync_schedule IS NOT NULL
 AND NOT (s.name = ANY($1::text[]))
 AND (rs.lease_id IS NULL OR rs.lease_expires_at <= clock_timestamp() OR rs.lease_generation <> s.definition_generation)
 AND (rs.ended_at IS NULL OR rs.ended_at + s.sync_schedule <= clock_timestamp()
      OR rs.observed_generation IS DISTINCT FROM s.definition_generation)
ORDER BY rs.ended_at ASC NULLS FIRST, s.name COLLATE "C"
LIMIT 1 FOR UPDATE OF s SKIP LOCKED
`

func (q *Queries) JobNext(ctx context.Context, dollar_1 []string) (string, error) {
	row := q.db.QueryRow(ctx, jobNext, dollar_1)
	var name string
	err := row.Scan(&name)
	return name, err
}

const jobRenew = `-- name: JobRenew :one
UPDATE registry_sync SET lease_expires_at=clock_timestamp()+($4::bigint * interval '1 microsecond')
WHERE source_id=$1::uuid AND lease_id=$2::uuid AND lease_generation=$3::bigint
 AND sync_status='IN_PROGRESS' AND lease_expires_at>clock_timestamp()
 AND lease_generation=(SELECT definition_generation FROM source WHERE id=$1::uuid)
RETURNING lease_expires_at
`

type JobRenewParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Column2 uuid.UUID `json:"column_2"`
	Column3 int64     `json:"column_3"`
	Column4 int64     `json:"column_4"`
}

func (q *Queries) JobRenew(ctx context.Context, arg JobRenewParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, jobRenew,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Column4,
	)
	var lease_expires_at pgtype.Timestamptz
	err := row.Scan(&lease_expires_at)
	return lease_expires_at, err
}

const jobSnapshotAllowed = `-- name: JobSnapshotAllowed :one
SELECT NOT EXISTS(SELECT 1 FROM registry_sync WHERE source_id=$1::uuid
 AND lease_id IS NOT NULL AND lease_expires_at>clock_timestamp()
 AND lease_generation=(SELECT definition_generation FROM source WHERE id=$1::uuid))
`

func (q *Queries) JobSnapshotAllowed(ctx context.Context, dollar_1 uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, jobSnapshotAllowed, dollar_1)
	var not_exists bool
	err := row.Scan(&not_exists)
	return not_exists, err
}

const jobStatus = `-- name: JobStatus :one
SELECT s.id::text AS source_id, COALESCE(rs.sync_status::text,'PENDING')::text AS phase, rs.attempt_count, rs.started_at,
 rs.ended_at, rs.lease_expires_at, rs.last_sync_hash,rs.last_applied_filter_hash,
 rs.server_count,rs.skill_count,rs.plugin_count,rs.error_msg,
 (rs.applied_generation=s.definition_generation AND rs.last_sync_hash IS NOT NULL
  AND rs.last_applied_filter_hash IS NOT NULL) AS baseline_valid
FROM source s LEFT JOIN registry_sync rs ON rs.source_id=s.id WHERE s.name=$1
`

type JobStatusRow struct {
	SourceID              string             `json:"source_id"`
	Phase                 string             `json:"phase"`
	AttemptCount          pgtype.Int8        `json:"attempt_count"`
	StartedAt             *time.Time         `json:"started_at"`
	EndedAt               *time.Time         `json:"ended_at"`
	LeaseExpiresAt        pgtype.Timestamptz `json:"lease_expires_at"`
	LastSyncHash          *string            `json:"last_sync_hash"`
	LastAppliedFilterHash *string            `json:"last_applied_filter_hash"`
	ServerCount           pgtype.Int8        `json:"server_count"`
	SkillCount            pgtype.Int8        `json:"skill_count"`
	PluginCount           pgtype.Int8        `json:"plugin_count"`
	ErrorMsg              *string            `json:"error_msg"`
	BaselineValid         pgtype.Bool        `json:"baseline_valid"`
}

func (q *Queries) JobStatus(ctx context.Context, name string) (JobStatusRow, error) {
	row := q.db.QueryRow(ctx, jobStatus, name)
	var i JobStatusRow
	err := row.Scan(
		&i.SourceID,
		&i.Phase,
		&i.AttemptCount,
		&i.StartedAt,
		&i.EndedAt,
		&i.LeaseExpiresAt,
		&i.LastSyncHash,
		&i.LastAppliedFilterHash,
		&i.ServerCount,
		&i.SkillCount,
		&i.PluginCount,
		&i.ErrorMsg,
		&i.BaselineValid,
	)
	return i, err
}
