// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plugins.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deletePluginGitPackagesByPluginId = `-- name: DeletePluginGitPackagesByPluginId :exec
DELETE FROM plugin_git_package WHERE plugin_id = $1
`

func (q *Queries) DeletePluginGitPackagesByPluginId(ctx context.Context, pluginID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePluginGitPackagesByPluginId, pluginID)
	return err
}

const deletePluginOciPackagesByPluginId = `-- name: DeletePluginOciPackagesByPluginId :exec
DELETE FROM plugin_oci_package WHERE plugin_id = $1
`

func (q *Queries) DeletePluginOciPackagesByPluginId(ctx context.Context, pluginID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePluginOciPackagesByPluginId, pluginID)
	return err
}

const deletePluginsByRegistry = `-- name: DeletePluginsByRegistry :exec
WITH plugin_entries AS (
    SELECT DISTINCT v.entry_id
      FROM entry_version v
      JOIN registry_entry e ON v.entry_id = e.id
      JOIN plugin p ON v.id = p.version_id
     WHERE e.source_id = $1
)
DELETE FROM registry_entry
 WHERE id IN (SELECT entry_id FROM plugin_entries)
`

func (q *Queries) DeletePluginsByRegistry(ctx context.Context, sourceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePluginsByRegistry, sourceID)
	return err
}

const getPluginVersion = `-- name: GetPluginVersion :many
SELECT src.source_type AS registry_type,
       v.id,
       e.name,
       v.version,
       (l.latest_version_id IS NOT NULL)::boolean AS is_latest,
       v.created_at,
       v.updated_at,
       v.description,
       v.title,
       p.version_id AS plugin_version_id,
       p.namespace,
       p.status,
       p.license,
       p.repository,
       p.icons,
       p.metadata,
       p.extension_meta,
       e.claims,
       rs.source_id,
       -- Sources not linked to the requested registry have no position; default to max int16
       -- so they sort after all explicitly positioned sources (lower position = higher priority).
       COALESCE(rs.position, 32767)::integer AS position
  FROM entry_version v
  JOIN registry_entry e ON e.id = v.entry_id
  JOIN registry_source rs ON rs.source_id = e.source_id
                          AND rs.registry_id = $1::uuid
  JOIN source src ON e.source_id = src.id
  JOIN plugin p ON p.version_id = v.id
  LEFT JOIN latest_entry_version l ON v.id = l.latest_version_id
 WHERE v.name = $2
   AND (v.version = $3::text
       OR ($3::text = 'latest' AND l.latest_version_id = v.id)
       )
   AND ($4::text IS NULL OR src.name = $4::text)
   AND ($5::text IS NULL OR p.namespace = $5::text)
   AND (
       $6::integer IS NULL
       OR (rs.position > $6::integer
           AND rs.source_id > $7::uuid
       )
   )
 ORDER BY rs.position ASC, rs.source_id ASC
 LIMIT $8::bigint
`

type GetPluginVersionParams struct {
	RegistryID     uuid.UUID   `json:"registry_id"`
	Name           string      `json:"name"`
	Version        string      `json:"version"`
	SourceName     *string     `json:"source_name"`
	Namespace      *string     `json:"namespace"`
	CursorPosition pgtype.Int4 `json:"cursor_position"`
	CursorSourceID *uuid.UUID  `json:"cursor_source_id"`
	Size           int64       `json:"size"`
}

type GetPluginVersionRow struct {
	RegistryType    string       `json:"registry_type"`
	ID              uuid.UUID    `json:"id"`
	Name            string       `json:"name"`
	Version         string       `json:"version"`
	IsLatest        bool         `json:"is_latest"`
	CreatedAt       *time.Time   `json:"created_at"`
	UpdatedAt       *time.Time   `json:"updated_at"`
	Description     *string      `json:"description"`
	Title           *string      `json:"title"`
	PluginVersionID uuid.UUID    `json:"plugin_version_id"`
	Namespace       string       `json:"namespace"`
	Status          PluginStatus `json:"status"`
	License         *string      `json:"license"`
	Repository      []byte       `json:"repository"`
	Icons           []byte       `json:"icons"`
	Metadata        []byte       `json:"metadata"`
	ExtensionMeta   []byte       `json:"extension_meta"`
	Claims          []byte       `json:"claims"`
	SourceID        uuid.UUID    `json:"source_id"`
	Position        int32        `json:"position"`
}

// Despite the name, this query returns multiple rows. The actual number of
// records is bounded by the number of sources that provide the same name and
// version, which we currently don't expect to be more than a few.
// Cursor-based pagination using (position, source_id) compound cursor.
// position is the sort key but may not be unique; source_id is the tiebreaker.
func (q *Queries) GetPluginVersion(ctx context.Context, arg GetPluginVersionParams) ([]GetPluginVersionRow, error) {
	rows, err := q.db.Query(ctx, getPluginVersion,
		arg.RegistryID,
		arg.Name,
		arg.Version,
		arg.SourceName,
		arg.Namespace,
		arg.CursorPosition,
		arg.CursorSourceID,
		arg.Size,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPluginVersionRow{}
	for rows.Next() {
		var i GetPluginVersionRow
		if err := rows.Scan(
			&i.RegistryType,
			&i.ID,
			&i.Name,
			&i.Version,
			&i.IsLatest,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.Title,
			&i.PluginVersionID,
			&i.Namespace,
			&i.Status,
			&i.License,
			&i.Repository,
			&i.Icons,
			&i.Metadata,
			&i.ExtensionMeta,
			&i.Claims,
			&i.SourceID,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPluginVersionBySourceName = `-- name: GetPluginVersionBySourceName :one
SELECT src.source_type AS registry_type,
       v.id,
       e.name,
       v.version,
       (l.latest_version_id IS NOT NULL)::boolean AS is_latest,
       v.created_at,
       v.updated_at,
       v.description,
       v.title,
       p.version_id AS plugin_version_id,
       p.namespace,
       p.status,
       p.license,
       p.repository,
       p.icons,
       p.metadata,
       p.extension_meta,
       e.claims,
       0::integer AS position
  FROM plugin p
  JOIN entry_version v ON p.version_id = v.id
  JOIN registry_entry e ON v.entry_id = e.id
  JOIN source src ON e.source_id = src.id
  LEFT JOIN latest_entry_version l ON v.id = l.latest_version_id
 WHERE v.name = $1
   AND v.version = $2
   AND src.name = $3
`

type GetPluginVersionBySourceNameParams struct {
	Name       string `json:"name"`
	Version    string `json:"version"`
	SourceName string `json:"source_name"`
}

type GetPluginVersionBySourceNameRow struct {
	RegistryType    string       `json:"registry_type"`
	ID              uuid.UUID    `json:"id"`
	Name            string       `json:"name"`
	Version         string       `json:"version"`
	IsLatest        bool         `json:"is_latest"`
	CreatedAt       *time.Time   `json:"created_at"`
	UpdatedAt       *time.Time   `json:"updated_at"`
	Description     *string      `json:"description"`
	Title           *string      `json:"title"`
	PluginVersionID uuid.UUID    `json:"plugin_version_id"`
	Namespace       string       `json:"namespace"`
	Status          PluginStatus `json:"status"`
	License         *string      `json:"license"`
	Repository      []byte       `json:"repository"`
	Icons           []byte       `json:"icons"`
	Metadata        []byte       `json:"metadata"`
	ExtensionMeta   []byte       `json:"extension_meta"`
	Claims          []byte       `json:"claims"`
	Position        int32        `json:"position"`
}

// Source-scoped variant of GetPluginVersion used by the publish fetch-back path.
// source_name and version are required; registry filtering is not applied.
func (q *Queries) GetPluginVersionBySourceName(ctx context.Context, arg GetPluginVersionBySourceNameParams) (GetPluginVersionBySourceNameRow, error) {
	row := q.db.QueryRow(ctx, getPluginVersionBySourceName, arg.Name, arg.Version, arg.SourceName)
	var i GetPluginVersionBySourceNameRow
	err := row.Scan(
		&i.RegistryType,
		&i.ID,
		&i.Name,
		&i.Version,
		&i.IsLatest,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		&i.Title,
		&i.PluginVersionID,
		&i.Namespace,
		&i.Status,
		&i.License,
		&i.Repository,
		&i.Icons,
		&i.Metadata,
		&i.ExtensionMeta,
		&i.Claims,
		&i.Position,
	)
	return i, err
}

const insertPluginGitPackage = `-- name: InsertPluginGitPackage :exec
INSERT INTO plugin_git_package (
    plugin_id,
    url,
    ref,
    commit_sha,
    subfolder
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type InsertPluginGitPackageParams struct {
	PluginID  uuid.UUID `json:"plugin_id"`
	Url       string    `json:"url"`
	Ref       *string   `json:"ref"`
	CommitSha *string   `json:"commit_sha"`
	Subfolder *string   `json:"subfolder"`
}

func (q *Queries) InsertPluginGitPackage(ctx context.Context, arg InsertPluginGitPackageParams) error {
	_, err := q.db.Exec(ctx, insertPluginGitPackage,
		arg.PluginID,
		arg.Url,
		arg.Ref,
		arg.CommitSha,
		arg.Subfolder,
	)
	return err
}

const insertPluginOciPackage = `-- name: InsertPluginOciPackage :exec
INSERT INTO plugin_oci_package (
    plugin_id,
    identifier,
    digest,
    media_type
) VALUES (
    $1,
    $2,
    $3,
    $4
)
`

type InsertPluginOciPackageParams struct {
	PluginID   uuid.UUID `json:"plugin_id"`
	Identifier string    `json:"identifier"`
	Digest     *string   `json:"digest"`
	MediaType  *string   `json:"media_type"`
}

func (q *Queries) InsertPluginOciPackage(ctx context.Context, arg InsertPluginOciPackageParams) error {
	_, err := q.db.Exec(ctx, insertPluginOciPackage,
		arg.PluginID,
		arg.Identifier,
		arg.Digest,
		arg.MediaType,
	)
	return err
}

const insertPluginVersion = `-- name: InsertPluginVersion :one
INSERT INTO plugin (
    version_id,
    namespace,
    status,
    license,
    repository,
    icons,
    metadata,
    extension_meta
) VALUES (
    $1,
    $2,
    COALESCE($3::plugin_status, 'ACTIVE'),
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING version_id
`

type InsertPluginVersionParams struct {
	VersionID     uuid.UUID        `json:"version_id"`
	Namespace     string           `json:"namespace"`
	Status        NullPluginStatus `json:"status"`
	License       *string          `json:"license"`
	Repository    []byte           `json:"repository"`
	Icons         []byte           `json:"icons"`
	Metadata      []byte           `json:"metadata"`
	ExtensionMeta []byte           `json:"extension_meta"`
}

func (q *Queries) InsertPluginVersion(ctx context.Context, arg InsertPluginVersionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertPluginVersion,
		arg.VersionID,
		arg.Namespace,
		arg.Status,
		arg.License,
		arg.Repository,
		arg.Icons,
		arg.Metadata,
		arg.ExtensionMeta,
	)
	var version_id uuid.UUID
	err := row.Scan(&version_id)
	return version_id, err
}

const insertPluginVersionForSync = `-- name: InsertPluginVersionForSync :one
INSERT INTO plugin (
    version_id,
    namespace,
    status,
    license,
    repository,
    icons,
    metadata,
    extension_meta
) VALUES (
    $1,
    $2,
    COALESCE($3::plugin_status, 'ACTIVE'),
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING version_id
`

type InsertPluginVersionForSyncParams struct {
	VersionID     uuid.UUID        `json:"version_id"`
	Namespace     string           `json:"namespace"`
	Status        NullPluginStatus `json:"status"`
	License       *string          `json:"license"`
	Repository    []byte           `json:"repository"`
	Icons         []byte           `json:"icons"`
	Metadata      []byte           `json:"metadata"`
	ExtensionMeta []byte           `json:"extension_meta"`
}

func (q *Queries) InsertPluginVersionForSync(ctx context.Context, arg InsertPluginVersionForSyncParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertPluginVersionForSync,
		arg.VersionID,
		arg.Namespace,
		arg.Status,
		arg.License,
		arg.Repository,
		arg.Icons,
		arg.Metadata,
		arg.ExtensionMeta,
	)
	var version_id uuid.UUID
	err := row.Scan(&version_id)
	return version_id, err
}

const listPluginGitPackages = `-- name: ListPluginGitPackages :many
SELECT p.id,
       p.plugin_id,
       p.url,
       p.ref,
       p.commit_sha,
       p.subfolder
  FROM plugin_git_package p
  JOIN plugin pl ON p.plugin_id = pl.version_id
 WHERE pl.version_id = ANY($1::UUID[])
`

func (q *Queries) ListPluginGitPackages(ctx context.Context, versionIds []uuid.UUID) ([]PluginGitPackage, error) {
	rows, err := q.db.Query(ctx, listPluginGitPackages, versionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PluginGitPackage{}
	for rows.Next() {
		var i PluginGitPackage
		if err := rows.Scan(
			&i.ID,
			&i.PluginID,
			&i.Url,
			&i.Ref,
			&i.CommitSha,
			&i.Subfolder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPluginOciPackages = `-- name: ListPluginOciPackages :many
SELECT p.id,
       p.plugin_id,
       p.identifier,
       p.digest,
       p.media_type
  FROM plugin_oci_package p
  JOIN plugin pl ON p.plugin_id = pl.version_id
 WHERE pl.version_id = ANY($1::UUID[])
`

func (q *Queries) ListPluginOciPackages(ctx context.Context, versionIds []uuid.UUID) ([]PluginOciPackage, error) {
	rows, err := q.db.Query(ctx, listPluginOciPackages, versionIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PluginOciPackage{}
	for rows.Next() {
		var i PluginOciPackage
		if err := rows.Scan(
			&i.ID,
			&i.PluginID,
			&i.Identifier,
			&i.Digest,
			&i.MediaType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlugins = `-- name: ListPlugins :many
SELECT src.source_type AS registry_type,
       p.version_id,
       e.name,
       v.version,
       (l.latest_version_id IS NOT NULL)::boolean AS is_latest,
       v.created_at,
       v.updated_at,
       v.description,
       v.title,
       p.namespace,
       p.status,
       p.license,
       p.repository,
       p.icons,
       p.metadata,
       p.extension_meta,
       e.claims,
       -- Sources not linked to the requested registry have no position; default to max int16
       -- so they sort after all explicitly positioned sources (lower position = higher priority).
       COALESCE(rs.position, 32767)::integer AS position
  FROM plugin p
  JOIN entry_version v ON p.version_id = v.id
  JOIN registry_entry e ON v.entry_id = e.id
  JOIN source src ON e.source_id = src.id
  LEFT JOIN latest_entry_version l ON v.id = l.latest_version_id
  JOIN registry_source rs ON rs.source_id = e.source_id
                          AND rs.registry_id = $1::uuid
 WHERE ($2::text IS NULL OR p.namespace = $2::text)
   AND ($3::text IS NULL OR e.name = $3::text)
   AND ($4::text IS NULL OR (
       LOWER(e.name) LIKE LOWER('%' || $4::text || '%')
       OR LOWER(v.title) LIKE LOWER('%' || $4::text || '%')
       OR LOWER(v.description) LIKE LOWER('%' || $4::text || '%')
   ))
   AND ($5::timestamp with time zone IS NULL OR v.updated_at > $5::timestamp with time zone)
   AND (
       $6::text IS NULL
       OR (v.name, v.version) > ($6::text, $7::text)
   )
 ORDER BY v.name ASC, v.version ASC, rs.position ASC
 LIMIT $8::bigint
`

type ListPluginsParams struct {
	RegistryID    uuid.UUID  `json:"registry_id"`
	Namespace     *string    `json:"namespace"`
	Name          *string    `json:"name"`
	Search        *string    `json:"search"`
	UpdatedSince  *time.Time `json:"updated_since"`
	CursorName    *string    `json:"cursor_name"`
	CursorVersion *string    `json:"cursor_version"`
	Size          int64      `json:"size"`
}

type ListPluginsRow struct {
	RegistryType  string       `json:"registry_type"`
	VersionID     uuid.UUID    `json:"version_id"`
	Name          string       `json:"name"`
	Version       string       `json:"version"`
	IsLatest      bool         `json:"is_latest"`
	CreatedAt     *time.Time   `json:"created_at"`
	UpdatedAt     *time.Time   `json:"updated_at"`
	Description   *string      `json:"description"`
	Title         *string      `json:"title"`
	Namespace     string       `json:"namespace"`
	Status        PluginStatus `json:"status"`
	License       *string      `json:"license"`
	Repository    []byte       `json:"repository"`
	Icons         []byte       `json:"icons"`
	Metadata      []byte       `json:"metadata"`
	ExtensionMeta []byte       `json:"extension_meta"`
	Claims        []byte       `json:"claims"`
	Position      int32        `json:"position"`
}

// Cursor-based pagination using (name, version) compound cursor.
// The cursor_name and cursor_version parameters define the starting point.
// When cursor is provided, results start AFTER the specified (name, version) tuple.
// Returns position from registry_source for source priority ordering.
func (q *Queries) ListPlugins(ctx context.Context, arg ListPluginsParams) ([]ListPluginsRow, error) {
	rows, err := q.db.Query(ctx, listPlugins,
		arg.RegistryID,
		arg.Namespace,
		arg.Name,
		arg.Search,
		arg.UpdatedSince,
		arg.CursorName,
		arg.CursorVersion,
		arg.Size,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPluginsRow{}
	for rows.Next() {
		var i ListPluginsRow
		if err := rows.Scan(
			&i.RegistryType,
			&i.VersionID,
			&i.Name,
			&i.Version,
			&i.IsLatest,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			&i.Title,
			&i.Namespace,
			&i.Status,
			&i.License,
			&i.Repository,
			&i.Icons,
			&i.Metadata,
			&i.ExtensionMeta,
			&i.Claims,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertLatestPluginVersion = `-- name: UpsertLatestPluginVersion :one
INSERT INTO latest_entry_version (
    source_id,
    name,
    version,
    latest_version_id
) VALUES (
    $1,
    $2,
    $3,
    $4
) ON CONFLICT (source_id, name)
  DO UPDATE SET
    version = $3,
    latest_version_id = $4
RETURNING latest_version_id
`

type UpsertLatestPluginVersionParams struct {
	SourceID  uuid.UUID `json:"source_id"`
	Name      string    `json:"name"`
	Version   string    `json:"version"`
	VersionID uuid.UUID `json:"version_id"`
}

func (q *Queries) UpsertLatestPluginVersion(ctx context.Context, arg UpsertLatestPluginVersionParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertLatestPluginVersion,
		arg.SourceID,
		arg.Name,
		arg.Version,
		arg.VersionID,
	)
	var latest_version_id uuid.UUID
	err := row.Scan(&latest_version_id)
	return latest_version_id, err
}

const upsertPluginVersionForSync = `-- name: UpsertPluginVersionForSync :one
INSERT INTO plugin (
    version_id,
    namespace,
    status,
    license,
    repository,
    icons,
    metadata,
    extension_meta
) VALUES (
    $1,
    $2,
    COALESCE($3::plugin_status, 'ACTIVE'),
    $4,
    $5,
    $6,
    $7,
    $8
)
ON CONFLICT (version_id)
DO UPDATE SET
    status = COALESCE($3::plugin_status, plugin.status),
    license = $4,
    repository = $5,
    icons = $6,
    metadata = $7,
    extension_meta = $8
RETURNING version_id
`

type UpsertPluginVersionForSyncParams struct {
	VersionID     uuid.UUID        `json:"version_id"`
	Namespace     string           `json:"namespace"`
	Status        NullPluginStatus `json:"status"`
	License       *string          `json:"license"`
	Repository    []byte           `json:"repository"`
	Icons         []byte           `json:"icons"`
	Metadata      []byte           `json:"metadata"`
	ExtensionMeta []byte           `json:"extension_meta"`
}

func (q *Queries) UpsertPluginVersionForSync(ctx context.Context, arg UpsertPluginVersionForSyncParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertPluginVersionForSync,
		arg.VersionID,
		arg.Namespace,
		arg.Status,
		arg.License,
		arg.Repository,
		arg.Icons,
		arg.Metadata,
		arg.ExtensionMeta,
	)
	var version_id uuid.UUID
	err := row.Scan(&version_id)
	return version_id, err
}
