// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: registry.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bulkUpsertRegistries = `-- name: BulkUpsertRegistries :many
INSERT INTO registry (
    name,
    reg_type,
    created_at,
    updated_at,
    is_managed
)
SELECT
    unnest($1::text[]),
    unnest($2::registry_type[]),
    unnest($3::timestamp with time zone[]),
    unnest($4::timestamp with time zone[]),
    unnest($5::boolean[])
ON CONFLICT (name) DO UPDATE SET
    reg_type = EXCLUDED.reg_type,
    updated_at = EXCLUDED.updated_at,
    is_managed = EXCLUDED.is_managed
RETURNING id, name
`

type BulkUpsertRegistriesParams struct {
	Names      []string       `json:"names"`
	RegTypes   []RegistryType `json:"reg_types"`
	CreatedAts []time.Time    `json:"created_ats"`
	UpdatedAts []time.Time    `json:"updated_ats"`
	IsManageds []bool         `json:"is_manageds"`
}

type BulkUpsertRegistriesRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) BulkUpsertRegistries(ctx context.Context, arg BulkUpsertRegistriesParams) ([]BulkUpsertRegistriesRow, error) {
	rows, err := q.db.Query(ctx, bulkUpsertRegistries,
		arg.Names,
		arg.RegTypes,
		arg.CreatedAts,
		arg.UpdatedAts,
		arg.IsManageds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BulkUpsertRegistriesRow{}
	for rows.Next() {
		var i BulkUpsertRegistriesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteRegistriesNotInList = `-- name: DeleteRegistriesNotInList :exec
DELETE FROM registry WHERE id NOT IN (SELECT unnest($1::uuid[]))
`

func (q *Queries) DeleteRegistriesNotInList(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRegistriesNotInList, ids)
	return err
}

const deleteRegistry = `-- name: DeleteRegistry :exec
DELETE FROM registry WHERE name = $1
`

func (q *Queries) DeleteRegistry(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteRegistry, name)
	return err
}

const getRegistry = `-- name: GetRegistry :one
SELECT id,
       name,
       reg_type,
       created_at,
       updated_at,
       is_managed
  FROM registry
 WHERE id = $1
`

func (q *Queries) GetRegistry(ctx context.Context, id uuid.UUID) (Registry, error) {
	row := q.db.QueryRow(ctx, getRegistry, id)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsManaged,
	)
	return i, err
}

const getRegistryByName = `-- name: GetRegistryByName :one
SELECT id,
       name,
       reg_type,
       created_at,
       updated_at,
       is_managed
  FROM registry
 WHERE name = $1
`

func (q *Queries) GetRegistryByName(ctx context.Context, name string) (Registry, error) {
	row := q.db.QueryRow(ctx, getRegistryByName, name)
	var i Registry
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RegType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsManaged,
	)
	return i, err
}

const insertRegistry = `-- name: InsertRegistry :one
INSERT INTO registry (
    name,
    reg_type,
    created_at,
    updated_at,
    is_managed
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id
`

type InsertRegistryParams struct {
	Name      string       `json:"name"`
	RegType   RegistryType `json:"reg_type"`
	CreatedAt *time.Time   `json:"created_at"`
	UpdatedAt *time.Time   `json:"updated_at"`
	IsManaged bool         `json:"is_managed"`
}

func (q *Queries) InsertRegistry(ctx context.Context, arg InsertRegistryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertRegistry,
		arg.Name,
		arg.RegType,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IsManaged,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listAllRegistryNames = `-- name: ListAllRegistryNames :many
SELECT name FROM registry ORDER BY name
`

func (q *Queries) ListAllRegistryNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listAllRegistryNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistries = `-- name: ListRegistries :many
SELECT id,
       name,
       reg_type,
       created_at,
       updated_at,
       is_managed
  FROM registry
 WHERE ($1::timestamp with time zone IS NULL OR created_at > $1)
   AND ($2::timestamp with time zone IS NULL OR created_at < $2)
 ORDER BY
  -- next page sorting
  CASE WHEN $1::timestamp with time zone IS NULL THEN created_at END ASC,
  CASE WHEN $1::timestamp with time zone IS NULL THEN name END ASC,
  -- previous page sorting
  CASE WHEN $2::timestamp with time zone IS NULL THEN created_at END DESC,
  CASE WHEN $2::timestamp with time zone IS NULL THEN name END DESC
 LIMIT $3::bigint
`

type ListRegistriesParams struct {
	Next *time.Time `json:"next"`
	Prev *time.Time `json:"prev"`
	Size int64      `json:"size"`
}

func (q *Queries) ListRegistries(ctx context.Context, arg ListRegistriesParams) ([]Registry, error) {
	rows, err := q.db.Query(ctx, listRegistries, arg.Next, arg.Prev, arg.Size)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Registry{}
	for rows.Next() {
		var i Registry
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RegType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsManaged,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRegistry = `-- name: UpsertRegistry :one
INSERT INTO registry (
    name,
    reg_type,
    created_at,
    updated_at,
    is_managed
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (name) DO UPDATE SET
    reg_type = EXCLUDED.reg_type,
    updated_at = EXCLUDED.updated_at,
    is_managed = EXCLUDED.is_managed
RETURNING id
`

type UpsertRegistryParams struct {
	Name      string       `json:"name"`
	RegType   RegistryType `json:"reg_type"`
	CreatedAt *time.Time   `json:"created_at"`
	UpdatedAt *time.Time   `json:"updated_at"`
	IsManaged bool         `json:"is_managed"`
}

func (q *Queries) UpsertRegistry(ctx context.Context, arg UpsertRegistryParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertRegistry,
		arg.Name,
		arg.RegType,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.IsManaged,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
