// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRegistrySync = `-- name: GetRegistrySync :one
SELECT id,
       reg_id,
       sync_status,
       error_msg,
       started_at,
       ended_at
FROM registry_sync
WHERE id = $1
`

func (q *Queries) GetRegistrySync(ctx context.Context, id pgtype.UUID) (RegistrySync, error) {
	row := q.db.QueryRow(ctx, getRegistrySync, id)
	var i RegistrySync
	err := row.Scan(
		&i.ID,
		&i.RegID,
		&i.SyncStatus,
		&i.ErrorMsg,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const insertRegistrySync = `-- name: InsertRegistrySync :one
INSERT INTO registry_sync (
    reg_id,
    sync_status,
    error_msg,
    started_at
) VALUES (
    $1,
    $2,
    $3,
    CURRENT_TIMESTAMP
) RETURNING id
`

type InsertRegistrySyncParams struct {
	RegID      pgtype.UUID `json:"reg_id"`
	SyncStatus SyncStatus  `json:"sync_status"`
	ErrorMsg   pgtype.Text `json:"error_msg"`
}

func (q *Queries) InsertRegistrySync(ctx context.Context, arg InsertRegistrySyncParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertRegistrySync, arg.RegID, arg.SyncStatus, arg.ErrorMsg)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const updateRegistrySync = `-- name: UpdateRegistrySync :exec
UPDATE registry_sync SET
    sync_status = $1,
    error_msg = $2,
    ended_at = $3
WHERE id = $4
`

type UpdateRegistrySyncParams struct {
	SyncStatus SyncStatus         `json:"sync_status"`
	ErrorMsg   pgtype.Text        `json:"error_msg"`
	EndedAt    pgtype.Timestamptz `json:"ended_at"`
	ID         pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateRegistrySync(ctx context.Context, arg UpdateRegistrySyncParams) error {
	_, err := q.db.Exec(ctx, updateRegistrySync,
		arg.SyncStatus,
		arg.ErrorMsg,
		arg.EndedAt,
		arg.ID,
	)
	return err
}
