# This Dockerfile is intended for docker-compose only.
FROM index.docker.io/library/golang@sha256:f60eaa87c79e604967c84d18fd3b151b3ee3f033bcdade4f3494e38411e60963 AS builder

USER root

WORKDIR /workspace

# Copy the Go Modules manifests
COPY go.mod go.mod
COPY go.sum go.sum
# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

ARG VERSION \
COMMIT \
BUILD_DATE

# Copy the entire Go module structure
COPY . .

# Build
RUN CGO_ENABLED=0 LDFLAGS="-s -w \
-X github.com/stacklok/toolhive/pkg/versions.Version=${VERSION} \
-X github.com/stacklok/toolhive/pkg/versions.Commit=${COMMIT} \
-X github.com/stacklok/toolhive/pkg/versions.BuildDate=${BUILD_DATE} \
-X github.com/stacklok/toolhive/pkg/versions.BuildType=release" \
GOOS=linux go build -ldflags "${LDFLAGS}" -o main ./cmd/thv-registry-api/main.go

# Use minimal base image to package the binary
FROM index.docker.io/library/alpine@sha256:4b7ce07002c69e8f3d704a9c5d6fd3053be500b7f1c69fc0d80990c2ad8dd412

COPY --from=builder /workspace/main /
COPY docker/entrypoint.sh /entrypoint.sh
COPY LICENSE /licenses/LICENSE

# Create working directory and data directory with proper permissions
# Make entrypoint script executable
RUN mkdir -p /app/data && \
    chown -R 1001:1001 /app && \
    chmod +x /entrypoint.sh

WORKDIR /app

USER 1001

ENTRYPOINT ["/entrypoint.sh"]
