// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_service.go -package=mocks -source=service.go Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/stacklok/toolhive/cmd/thv-registry-api/internal/service"
	registry "github.com/stacklok/toolhive/pkg/registry"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistryService is a mock of RegistryService interface.
type MockRegistryService struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryServiceMockRecorder
	isgomock struct{}
}

// MockRegistryServiceMockRecorder is the mock recorder for MockRegistryService.
type MockRegistryServiceMockRecorder struct {
	mock *MockRegistryService
}

// NewMockRegistryService creates a new mock instance.
func NewMockRegistryService(ctrl *gomock.Controller) *MockRegistryService {
	mock := &MockRegistryService{ctrl: ctrl}
	mock.recorder = &MockRegistryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistryService) EXPECT() *MockRegistryServiceMockRecorder {
	return m.recorder
}

// CheckReadiness mocks base method.
func (m *MockRegistryService) CheckReadiness(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckReadiness", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckReadiness indicates an expected call of CheckReadiness.
func (mr *MockRegistryServiceMockRecorder) CheckReadiness(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckReadiness", reflect.TypeOf((*MockRegistryService)(nil).CheckReadiness), ctx)
}

// GetDeployedServer mocks base method.
func (m *MockRegistryService) GetDeployedServer(ctx context.Context, name string) ([]*service.DeployedServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeployedServer", ctx, name)
	ret0, _ := ret[0].([]*service.DeployedServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeployedServer indicates an expected call of GetDeployedServer.
func (mr *MockRegistryServiceMockRecorder) GetDeployedServer(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeployedServer", reflect.TypeOf((*MockRegistryService)(nil).GetDeployedServer), ctx, name)
}

// GetRegistry mocks base method.
func (m *MockRegistryService) GetRegistry(ctx context.Context) (*registry.Registry, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistry", ctx)
	ret0, _ := ret[0].(*registry.Registry)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetRegistry indicates an expected call of GetRegistry.
func (mr *MockRegistryServiceMockRecorder) GetRegistry(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistry", reflect.TypeOf((*MockRegistryService)(nil).GetRegistry), ctx)
}

// GetServer mocks base method.
func (m *MockRegistryService) GetServer(ctx context.Context, name string) (registry.ServerMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetServer", ctx, name)
	ret0, _ := ret[0].(registry.ServerMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServer indicates an expected call of GetServer.
func (mr *MockRegistryServiceMockRecorder) GetServer(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServer", reflect.TypeOf((*MockRegistryService)(nil).GetServer), ctx, name)
}

// ListDeployedServers mocks base method.
func (m *MockRegistryService) ListDeployedServers(ctx context.Context) ([]*service.DeployedServer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeployedServers", ctx)
	ret0, _ := ret[0].([]*service.DeployedServer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeployedServers indicates an expected call of ListDeployedServers.
func (mr *MockRegistryServiceMockRecorder) ListDeployedServers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeployedServers", reflect.TypeOf((*MockRegistryService)(nil).ListDeployedServers), ctx)
}

// ListServers mocks base method.
func (m *MockRegistryService) ListServers(ctx context.Context) ([]registry.ServerMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListServers", ctx)
	ret0, _ := ret[0].([]registry.ServerMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListServers indicates an expected call of ListServers.
func (mr *MockRegistryServiceMockRecorder) ListServers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListServers", reflect.TypeOf((*MockRegistryService)(nil).ListServers), ctx)
}
