// Code generated by MockGen. DO NOT EDIT.
// Source: provider.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_provider.go -package=mocks -source=provider.go RegistryDataProvider,DeploymentProvider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	registry "github.com/stacklok/toolhive/pkg/registry/registry"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistryDataProvider is a mock of RegistryDataProvider interface.
type MockRegistryDataProvider struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryDataProviderMockRecorder
	isgomock struct{}
}

// MockRegistryDataProviderMockRecorder is the mock recorder for MockRegistryDataProvider.
type MockRegistryDataProviderMockRecorder struct {
	mock *MockRegistryDataProvider
}

// NewMockRegistryDataProvider creates a new mock instance.
func NewMockRegistryDataProvider(ctrl *gomock.Controller) *MockRegistryDataProvider {
	mock := &MockRegistryDataProvider{ctrl: ctrl}
	mock.recorder = &MockRegistryDataProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistryDataProvider) EXPECT() *MockRegistryDataProviderMockRecorder {
	return m.recorder
}

// GetRegistryData mocks base method.
func (m *MockRegistryDataProvider) GetRegistryData(ctx context.Context) (*registry.UpstreamRegistry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistryData", ctx)
	ret0, _ := ret[0].(*registry.UpstreamRegistry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegistryData indicates an expected call of GetRegistryData.
func (mr *MockRegistryDataProviderMockRecorder) GetRegistryData(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistryData", reflect.TypeOf((*MockRegistryDataProvider)(nil).GetRegistryData), ctx)
}

// GetRegistryName mocks base method.
func (m *MockRegistryDataProvider) GetRegistryName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegistryName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetRegistryName indicates an expected call of GetRegistryName.
func (mr *MockRegistryDataProviderMockRecorder) GetRegistryName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegistryName", reflect.TypeOf((*MockRegistryDataProvider)(nil).GetRegistryName))
}

// GetSource mocks base method.
func (m *MockRegistryDataProvider) GetSource() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSource")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetSource indicates an expected call of GetSource.
func (mr *MockRegistryDataProviderMockRecorder) GetSource() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSource", reflect.TypeOf((*MockRegistryDataProvider)(nil).GetSource))
}
