version: '3'

tasks:
  registry-build:
    desc: Build the registry API binary
    cmds:
      - go build -o bin/thv-registry-api ./cmd/thv-registry-api

  registry-build-image:
    desc: Build the registry API image with ko
    env:
      KO_DOCKER_REPO: ghcr.io/stacklok/toolhive-registry-server
    cmds:
      - ko build --local -B ./cmd/thv-registry-api

  registry-test:
    desc: Run registry API tests
    dir: cmd/thv-registry-api
    cmds:
      - go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest
      # we have to use ldflags to avoid the LC_DYSYMTAB linker error. 
      # https://github.com/stacklok/toolhive/issues/1687
      - go test -ldflags=-extldflags=-Wl,-w -race $(go list ./... | grep -v '/test-integration')  | gotestfmt -hide "all"