version: '3'

tasks:
  registry-build:
    desc: Build the registry API binary
    cmds:
      - go build -o bin/thv-registry-api ./cmd/thv-registry-api

  registry-build-image:
    desc: Build the registry API image with ko
    env:
      KO_DOCKER_REPO: ghcr.io/stacklok/toolhive
    cmds:
      - ko build --local -B ./cmd/thv-registry-api

  registry-test:
    desc: Run registry API tests
    dir: cmd/thv-registry-api
    cmds:
      - go test ./api/v1 -v
