// Code generated by MockGen. DO NOT EDIT.
// Source: persistence.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_status_persistence.go -package=mocks -source=persistence.go StatusPersistence
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	status "github.com/stacklok/toolhive-registry-server/internal/status"
	gomock "go.uber.org/mock/gomock"
)

// MockStatusPersistence is a mock of StatusPersistence interface.
type MockStatusPersistence struct {
	ctrl     *gomock.Controller
	recorder *MockStatusPersistenceMockRecorder
	isgomock struct{}
}

// MockStatusPersistenceMockRecorder is the mock recorder for MockStatusPersistence.
type MockStatusPersistenceMockRecorder struct {
	mock *MockStatusPersistence
}

// NewMockStatusPersistence creates a new mock instance.
func NewMockStatusPersistence(ctrl *gomock.Controller) *MockStatusPersistence {
	mock := &MockStatusPersistence{ctrl: ctrl}
	mock.recorder = &MockStatusPersistenceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatusPersistence) EXPECT() *MockStatusPersistenceMockRecorder {
	return m.recorder
}

// LoadAllStatus mocks base method.
func (m *MockStatusPersistence) LoadAllStatus(ctx context.Context) (map[string]*status.SyncStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadAllStatus", ctx)
	ret0, _ := ret[0].(map[string]*status.SyncStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadAllStatus indicates an expected call of LoadAllStatus.
func (mr *MockStatusPersistenceMockRecorder) LoadAllStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadAllStatus", reflect.TypeOf((*MockStatusPersistence)(nil).LoadAllStatus), ctx)
}

// LoadStatus mocks base method.
func (m *MockStatusPersistence) LoadStatus(ctx context.Context, registryName string) (*status.SyncStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadStatus", ctx, registryName)
	ret0, _ := ret[0].(*status.SyncStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadStatus indicates an expected call of LoadStatus.
func (mr *MockStatusPersistenceMockRecorder) LoadStatus(ctx, registryName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadStatus", reflect.TypeOf((*MockStatusPersistence)(nil).LoadStatus), ctx, registryName)
}

// SaveStatus mocks base method.
func (m *MockStatusPersistence) SaveStatus(ctx context.Context, registryName string, arg2 *status.SyncStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveStatus", ctx, registryName, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveStatus indicates an expected call of SaveStatus.
func (mr *MockStatusPersistenceMockRecorder) SaveStatus(ctx, registryName, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveStatus", reflect.TypeOf((*MockStatusPersistence)(nil).SaveStatus), ctx, registryName, arg2)
}
