// Code generated by MockGen. DO NOT EDIT.
// Source: storage_manager.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_storage_manager.go -package=mocks -source=storage_manager.go StorageManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	config "github.com/stacklok/toolhive-registry-server/internal/config"
	types "github.com/stacklok/toolhive/pkg/registry/types"
	gomock "go.uber.org/mock/gomock"
)

// MockStorageManager is a mock of StorageManager interface.
type MockStorageManager struct {
	ctrl     *gomock.Controller
	recorder *MockStorageManagerMockRecorder
	isgomock struct{}
}

// MockStorageManagerMockRecorder is the mock recorder for MockStorageManager.
type MockStorageManagerMockRecorder struct {
	mock *MockStorageManager
}

// NewMockStorageManager creates a new mock instance.
func NewMockStorageManager(ctrl *gomock.Controller) *MockStorageManager {
	mock := &MockStorageManager{ctrl: ctrl}
	mock.recorder = &MockStorageManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageManager) EXPECT() *MockStorageManagerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockStorageManager) Delete(ctx context.Context, cfg *config.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStorageManagerMockRecorder) Delete(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStorageManager)(nil).Delete), ctx, cfg)
}

// Get mocks base method.
func (m *MockStorageManager) Get(ctx context.Context, cfg *config.Config) (*types.UpstreamRegistry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, cfg)
	ret0, _ := ret[0].(*types.UpstreamRegistry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStorageManagerMockRecorder) Get(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStorageManager)(nil).Get), ctx, cfg)
}

// Store mocks base method.
func (m *MockStorageManager) Store(ctx context.Context, cfg *config.Config, reg *types.UpstreamRegistry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, cfg, reg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockStorageManagerMockRecorder) Store(ctx, cfg, reg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockStorageManager)(nil).Store), ctx, cfg, reg)
}
