// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_source_handler.go -package=mocks -source=types.go SourceHandler,SourceHandlerFactory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	config "github.com/stacklok/toolhive-registry-server/internal/config"
	sources "github.com/stacklok/toolhive-registry-server/internal/sources"
	registry "github.com/stacklok/toolhive/pkg/registry/registry"
	gomock "go.uber.org/mock/gomock"
)

// MockSourceDataValidator is a mock of SourceDataValidator interface.
type MockSourceDataValidator struct {
	ctrl     *gomock.Controller
	recorder *MockSourceDataValidatorMockRecorder
	isgomock struct{}
}

// MockSourceDataValidatorMockRecorder is the mock recorder for MockSourceDataValidator.
type MockSourceDataValidatorMockRecorder struct {
	mock *MockSourceDataValidator
}

// NewMockSourceDataValidator creates a new mock instance.
func NewMockSourceDataValidator(ctrl *gomock.Controller) *MockSourceDataValidator {
	mock := &MockSourceDataValidator{ctrl: ctrl}
	mock.recorder = &MockSourceDataValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceDataValidator) EXPECT() *MockSourceDataValidatorMockRecorder {
	return m.recorder
}

// ValidateData mocks base method.
func (m *MockSourceDataValidator) ValidateData(data []byte, format string) (*registry.UpstreamRegistry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateData", data, format)
	ret0, _ := ret[0].(*registry.UpstreamRegistry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateData indicates an expected call of ValidateData.
func (mr *MockSourceDataValidatorMockRecorder) ValidateData(data, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateData", reflect.TypeOf((*MockSourceDataValidator)(nil).ValidateData), data, format)
}

// MockSourceHandler is a mock of SourceHandler interface.
type MockSourceHandler struct {
	ctrl     *gomock.Controller
	recorder *MockSourceHandlerMockRecorder
	isgomock struct{}
}

// MockSourceHandlerMockRecorder is the mock recorder for MockSourceHandler.
type MockSourceHandlerMockRecorder struct {
	mock *MockSourceHandler
}

// NewMockSourceHandler creates a new mock instance.
func NewMockSourceHandler(ctrl *gomock.Controller) *MockSourceHandler {
	mock := &MockSourceHandler{ctrl: ctrl}
	mock.recorder = &MockSourceHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceHandler) EXPECT() *MockSourceHandlerMockRecorder {
	return m.recorder
}

// CurrentHash mocks base method.
func (m *MockSourceHandler) CurrentHash(ctx context.Context, regCfg *config.RegistryConfig) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentHash", ctx, regCfg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentHash indicates an expected call of CurrentHash.
func (mr *MockSourceHandlerMockRecorder) CurrentHash(ctx, regCfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentHash", reflect.TypeOf((*MockSourceHandler)(nil).CurrentHash), ctx, regCfg)
}

// FetchRegistry mocks base method.
func (m *MockSourceHandler) FetchRegistry(ctx context.Context, regCfg *config.RegistryConfig) (*sources.FetchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRegistry", ctx, regCfg)
	ret0, _ := ret[0].(*sources.FetchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRegistry indicates an expected call of FetchRegistry.
func (mr *MockSourceHandlerMockRecorder) FetchRegistry(ctx, regCfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRegistry", reflect.TypeOf((*MockSourceHandler)(nil).FetchRegistry), ctx, regCfg)
}

// Validate mocks base method.
func (m *MockSourceHandler) Validate(regCfg *config.RegistryConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", regCfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockSourceHandlerMockRecorder) Validate(regCfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockSourceHandler)(nil).Validate), regCfg)
}

// MockSourceHandlerFactory is a mock of SourceHandlerFactory interface.
type MockSourceHandlerFactory struct {
	ctrl     *gomock.Controller
	recorder *MockSourceHandlerFactoryMockRecorder
	isgomock struct{}
}

// MockSourceHandlerFactoryMockRecorder is the mock recorder for MockSourceHandlerFactory.
type MockSourceHandlerFactoryMockRecorder struct {
	mock *MockSourceHandlerFactory
}

// NewMockSourceHandlerFactory creates a new mock instance.
func NewMockSourceHandlerFactory(ctrl *gomock.Controller) *MockSourceHandlerFactory {
	mock := &MockSourceHandlerFactory{ctrl: ctrl}
	mock.recorder = &MockSourceHandlerFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceHandlerFactory) EXPECT() *MockSourceHandlerFactoryMockRecorder {
	return m.recorder
}

// CreateHandler mocks base method.
func (m *MockSourceHandlerFactory) CreateHandler(regCfg *config.RegistryConfig) (sources.SourceHandler, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHandler", regCfg)
	ret0, _ := ret[0].(sources.SourceHandler)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHandler indicates an expected call of CreateHandler.
func (mr *MockSourceHandlerFactoryMockRecorder) CreateHandler(regCfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHandler", reflect.TypeOf((*MockSourceHandlerFactory)(nil).CreateHandler), regCfg)
}
