// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/stacklok/toolhive-registry-server/pkg/sync (interfaces: Manager)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_manager.go -package=mocks github.com/stacklok/toolhive-registry-server/pkg/sync Manager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	config "github.com/stacklok/toolhive-registry-server/pkg/config"
	status "github.com/stacklok/toolhive-registry-server/pkg/status"
	sync "github.com/stacklok/toolhive-registry-server/pkg/sync"
	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockManager) Delete(ctx context.Context, arg1 *config.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockManagerMockRecorder) Delete(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockManager)(nil).Delete), ctx, arg1)
}

// PerformSync mocks base method.
func (m *MockManager) PerformSync(ctx context.Context, arg1 *config.Config) (*sync.Result, *sync.Error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PerformSync", ctx, arg1)
	ret0, _ := ret[0].(*sync.Result)
	ret1, _ := ret[1].(*sync.Error)
	return ret0, ret1
}

// PerformSync indicates an expected call of PerformSync.
func (mr *MockManagerMockRecorder) PerformSync(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerformSync", reflect.TypeOf((*MockManager)(nil).PerformSync), ctx, arg1)
}

// ShouldSync mocks base method.
func (m *MockManager) ShouldSync(ctx context.Context, arg1 *config.Config, syncStatus *status.SyncStatus, manualSyncRequested bool) (bool, string, *time.Time) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldSync", ctx, arg1, syncStatus, manualSyncRequested)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(*time.Time)
	return ret0, ret1, ret2
}

// ShouldSync indicates an expected call of ShouldSync.
func (mr *MockManagerMockRecorder) ShouldSync(ctx, arg1, syncStatus, manualSyncRequested any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldSync", reflect.TypeOf((*MockManager)(nil).ShouldSync), ctx, arg1, syncStatus, manualSyncRequested)
}
