// Package v01 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v01

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for IconMimeType.
const (
	Imagejpeg   IconMimeType = "image/jpeg"
	Imagejpg    IconMimeType = "image/jpg"
	Imagepng    IconMimeType = "image/png"
	ImagesvgXml IconMimeType = "image/svg+xml"
	Imagewebp   IconMimeType = "image/webp"
)

// Defines values for IconTheme.
const (
	Dark  IconTheme = "dark"
	Light IconTheme = "light"
)

// Defines values for InputFormat.
const (
	InputFormatBoolean  InputFormat = "boolean"
	InputFormatFilepath InputFormat = "filepath"
	InputFormatNumber   InputFormat = "number"
	InputFormatString   InputFormat = "string"
)

// Defines values for InputWithVariablesFormat.
const (
	InputWithVariablesFormatBoolean  InputWithVariablesFormat = "boolean"
	InputWithVariablesFormatFilepath InputWithVariablesFormat = "filepath"
	InputWithVariablesFormatNumber   InputWithVariablesFormat = "number"
	InputWithVariablesFormatString   InputWithVariablesFormat = "string"
)

// Defines values for KeyValueInputFormat.
const (
	KeyValueInputFormatBoolean  KeyValueInputFormat = "boolean"
	KeyValueInputFormatFilepath KeyValueInputFormat = "filepath"
	KeyValueInputFormatNumber   KeyValueInputFormat = "number"
	KeyValueInputFormatString   KeyValueInputFormat = "string"
)

// Defines values for NamedArgumentFormat.
const (
	NamedArgumentFormatBoolean  NamedArgumentFormat = "boolean"
	NamedArgumentFormatFilepath NamedArgumentFormat = "filepath"
	NamedArgumentFormatNumber   NamedArgumentFormat = "number"
	NamedArgumentFormatString   NamedArgumentFormat = "string"
)

// Defines values for NamedArgumentType.
const (
	Named NamedArgumentType = "named"
)

// Defines values for PositionalArgumentFormat.
const (
	Boolean  PositionalArgumentFormat = "boolean"
	Filepath PositionalArgumentFormat = "filepath"
	Number   PositionalArgumentFormat = "number"
	String   PositionalArgumentFormat = "string"
)

// Defines values for PositionalArgumentType.
const (
	Positional PositionalArgumentType = "positional"
)

// Defines values for ServerResponseMetaIoModelcontextprotocolRegistryofficialStatus.
const (
	Active     ServerResponseMetaIoModelcontextprotocolRegistryofficialStatus = "active"
	Deleted    ServerResponseMetaIoModelcontextprotocolRegistryofficialStatus = "deleted"
	Deprecated ServerResponseMetaIoModelcontextprotocolRegistryofficialStatus = "deprecated"
)

// Defines values for SseTransportType.
const (
	Sse SseTransportType = "sse"
)

// Defines values for StdioTransportType.
const (
	Stdio StdioTransportType = "stdio"
)

// Defines values for StreamableHttpTransportType.
const (
	StreamableHttp StreamableHttpTransportType = "streamable-http"
)

// Argument Warning: Arguments construct command-line parameters that may contain user-provided input. This creates potential command injection risks if clients execute commands in a shell environment. For example, a malicious argument value like ';rm -rf ~/Development' could execute dangerous commands. Clients should prefer non-shell execution methods (e.g., posix_spawn) when possible to eliminate injection risks entirely. Where not possible, clients should obtain consent from users or agents to run the resolved command before execution.
type Argument struct {
	union json.RawMessage
}

// Icon An optionally-sized icon that can be displayed in a user interface.
type Icon struct {
	// MimeType Optional MIME type override if the source MIME type is missing or generic. Must be one of: image/png, image/jpeg, image/jpg, image/svg+xml, image/webp.
	MimeType *IconMimeType `json:"mimeType,omitempty"`

	// Sizes Optional array of strings that specify sizes at which the icon can be used. Each string should be in WxH format (e.g., '48x48', '96x96') or 'any' for scalable formats like SVG. If not provided, the client should assume that the icon can be used at any size.
	Sizes *[]string `json:"sizes,omitempty"`

	// Src A standard URI pointing to an icon resource. Must be an HTTPS URL. Consumers SHOULD take steps to ensure URLs serving icons are from the same domain as the server or a trusted domain. Consumers SHOULD take appropriate precautions when consuming SVGs as they can contain executable JavaScript.
	Src string `json:"src"`

	// Theme Optional specifier for the theme this icon is designed for. 'light' indicates the icon is designed to be used with a light background, and 'dark' indicates the icon is designed to be used with a dark background. If not provided, the client should assume the icon can be used with any theme.
	Theme *IconTheme `json:"theme,omitempty"`
}

// IconMimeType Optional MIME type override if the source MIME type is missing or generic. Must be one of: image/png, image/jpeg, image/jpg, image/svg+xml, image/webp.
type IconMimeType string

// IconTheme Optional specifier for the theme this icon is designed for. 'light' indicates the icon is designed to be used with a light background, and 'dark' indicates the icon is designed to be used with a dark background. If not provided, the client should assume the icon can be used with any theme.
type IconTheme string

// Input defines model for Input.
type Input struct {
	// Choices A list of possible values for the input. If provided, the user must select one of these values.
	Choices *[]string `json:"choices,omitempty"`

	// Default The default value for the input.  This should be a valid value for the input.  If you want to provide input examples or guidance, use the `placeholder` field instead.
	Default *string `json:"default,omitempty"`

	// Description A description of the input, which clients can use to provide context to the user.
	Description *string `json:"description,omitempty"`

	// Format Specifies the input format. Supported values include `filepath`, which should be interpreted as a file on the user's filesystem.
	//
	// When the input is converted to a string, booleans should be represented by the strings "true" and "false", and numbers should be represented as decimal values.
	Format     *InputFormat `json:"format,omitempty"`
	IsRequired *bool        `json:"isRequired,omitempty"`

	// IsSecret Indicates whether the input is a secret value (e.g., password, token). If true, clients should handle the value securely.
	IsSecret *bool `json:"isSecret,omitempty"`

	// Placeholder A placeholder for the input to be displaying during configuration. This is used to provide examples or guidance about the expected form or content of the input.
	Placeholder *string `json:"placeholder,omitempty"`

	// Value The value for the input. If this is not set, the user may be prompted to provide a value. If a value is set, it should not be configurable by end users.
	//
	// Identifiers wrapped in `{curly_braces}` will be replaced with the corresponding properties from the input `variables` map. If an identifier in braces is not found in `variables`, or if `variables` is not provided, the `{curly_braces}` substring should remain unchanged.
	Value *string `json:"value,omitempty"`
}

// InputFormat Specifies the input format. Supported values include `filepath`, which should be interpreted as a file on the user's filesystem.
//
// When the input is converted to a string, booleans should be represented by the strings "true" and "false", and numbers should be represented as decimal values.
type InputFormat string

// InputWithVariables defines model for InputWithVariables.
type InputWithVariables struct {
	// Choices A list of possible values for the input. If provided, the user must select one of these values.
	Choices *[]string `json:"choices,omitempty"`

	// Default The default value for the input.  This should be a valid value for the input.  If you want to provide input examples or guidance, use the `placeholder` field instead.
	Default *string `json:"default,omitempty"`

	// Description A description of the input, which clients can use to provide context to the user.
	Description *string `json:"description,omitempty"`

	// Format Specifies the input format. Supported values include `filepath`, which should be interpreted as a file on the user's filesystem.
	//
	// When the input is converted to a string, booleans should be represented by the strings "true" and "false", and numbers should be represented as decimal values.
	Format     *InputWithVariablesFormat `json:"format,omitempty"`
	IsRequired *bool                     `json:"isRequired,omitempty"`

	// IsSecret Indicates whether the input is a secret value (e.g., password, token). If true, clients should handle the value securely.
	IsSecret *bool `json:"isSecret,omitempty"`

	// Placeholder A placeholder for the input to be displaying during configuration. This is used to provide examples or guidance about the expected form or content of the input.
	Placeholder *string `json:"placeholder,omitempty"`

	// Value The value for the input. If this is not set, the user may be prompted to provide a value. If a value is set, it should not be configurable by end users.
	//
	// Identifiers wrapped in `{curly_braces}` will be replaced with the corresponding properties from the input `variables` map. If an identifier in braces is not found in `variables`, or if `variables` is not provided, the `{curly_braces}` substring should remain unchanged.
	Value *string `json:"value,omitempty"`

	// Variables A map of variable names to their values. Keys in the input `value` that are wrapped in `{curly_braces}` will be replaced with the corresponding variable values.
	Variables *map[string]Input `json:"variables,omitempty"`
}

// InputWithVariablesFormat Specifies the input format. Supported values include `filepath`, which should be interpreted as a file on the user's filesystem.
//
// When the input is converted to a string, booleans should be represented by the strings "true" and "false", and numbers should be represented as decimal values.
type InputWithVariablesFormat string

// KeyValueInput defines model for KeyValueInput.
type KeyValueInput struct {
	// Choices A list of possible values for the input. If provided, the user must select one of these values.
	Choices *[]string `json:"choices,omitempty"`

	// Default The default value for the input.  This should be a valid value for the input.  If you want to provide input examples or guidance, use the `placeholder` field instead.
	Default *string `json:"default,omitempty"`

	// Description A description of the input, which clients can use to provide context to the user.
	Description *string `json:"description,omitempty"`

	// Format Specifies the input format. Supported values include `filepath`, which should be interpreted as a file on the user's filesystem.
	//
	// When the input is converted to a string, booleans should be represented by the strings "true" and "false", and numbers should be represented as decimal values.
	Format     *KeyValueInputFormat `json:"format,omitempty"`
	IsRequired *bool                `json:"isRequired,omitempty"`

	// IsSecret Indicates whether the input is a secret value (e.g., password, token). If true, clients should handle the value securely.
	IsSecret *bool `json:"isSecret,omitempty"`

	// Name Name of the header or environment variable.
	Name string `json:"name"`

	// Placeholder A placeholder for the input to be displaying during configuration. This is used to provide examples or guidance about the expected form or content of the input.
	Placeholder *string `json:"placeholder,omitempty"`

	// Value The value for the input. If this is not set, the user may be prompted to provide a value. If a value is set, it should not be configurable by end users.
	//
	// Identifiers wrapped in `{curly_braces}` will be replaced with the corresponding properties from the input `variables` map. If an identifier in braces is not found in `variables`, or if `variables` is not provided, the `{curly_braces}` substring should remain unchanged.
	Value *string `json:"value,omitempty"`

	// Variables A map of variable names to their values. Keys in the input `value` that are wrapped in `{curly_braces}` will be replaced with the corresponding variable values.
	Variables *map[string]Input `json:"variables,omitempty"`
}

// KeyValueInputFormat Specifies the input format. Supported values include `filepath`, which should be interpreted as a file on the user's filesystem.
//
// When the input is converted to a string, booleans should be represented by the strings "true" and "false", and numbers should be represented as decimal values.
type KeyValueInputFormat string

// NamedArgument defines model for NamedArgument.
type NamedArgument struct {
	// Choices A list of possible values for the input. If provided, the user must select one of these values.
	Choices *[]string `json:"choices,omitempty"`

	// Default The default value for the input.  This should be a valid value for the input.  If you want to provide input examples or guidance, use the `placeholder` field instead.
	Default *string `json:"default,omitempty"`

	// Description A description of the input, which clients can use to provide context to the user.
	Description *string `json:"description,omitempty"`

	// Format Specifies the input format. Supported values include `filepath`, which should be interpreted as a file on the user's filesystem.
	//
	// When the input is converted to a string, booleans should be represented by the strings "true" and "false", and numbers should be represented as decimal values.
	Format *NamedArgumentFormat `json:"format,omitempty"`

	// IsRepeated Whether the argument can be repeated multiple times.
	IsRepeated *bool `json:"isRepeated,omitempty"`
	IsRequired *bool `json:"isRequired,omitempty"`

	// IsSecret Indicates whether the input is a secret value (e.g., password, token). If true, clients should handle the value securely.
	IsSecret *bool `json:"isSecret,omitempty"`

	// Name The flag name, including any leading dashes.
	Name string `json:"name"`

	// Placeholder A placeholder for the input to be displaying during configuration. This is used to provide examples or guidance about the expected form or content of the input.
	Placeholder *string           `json:"placeholder,omitempty"`
	Type        NamedArgumentType `json:"type"`

	// Value The value for the input. If this is not set, the user may be prompted to provide a value. If a value is set, it should not be configurable by end users.
	//
	// Identifiers wrapped in `{curly_braces}` will be replaced with the corresponding properties from the input `variables` map. If an identifier in braces is not found in `variables`, or if `variables` is not provided, the `{curly_braces}` substring should remain unchanged.
	Value *string `json:"value,omitempty"`

	// Variables A map of variable names to their values. Keys in the input `value` that are wrapped in `{curly_braces}` will be replaced with the corresponding variable values.
	Variables *map[string]Input `json:"variables,omitempty"`
}

// NamedArgumentFormat Specifies the input format. Supported values include `filepath`, which should be interpreted as a file on the user's filesystem.
//
// When the input is converted to a string, booleans should be represented by the strings "true" and "false", and numbers should be represented as decimal values.
type NamedArgumentFormat string

// NamedArgumentType defines model for NamedArgument.Type.
type NamedArgumentType string

// Package defines model for Package.
type Package struct {
	// EnvironmentVariables A mapping of environment variables to be set when running the package.
	EnvironmentVariables *[]KeyValueInput `json:"environmentVariables,omitempty"`

	// FileSha256 SHA-256 hash of the package file for integrity verification. Required for MCPB packages and optional for other package types. Authors are responsible for generating correct SHA-256 hashes when creating server.json. If present, MCP clients must validate the downloaded file matches the hash before running packages to ensure file integrity.
	FileSha256 *string `json:"fileSha256,omitempty"`

	// Identifier Package identifier - either a package name (for registries) or URL (for direct downloads)
	Identifier string `json:"identifier"`

	// PackageArguments A list of arguments to be passed to the package's binary.
	PackageArguments *[]Argument `json:"packageArguments,omitempty"`

	// RegistryBaseUrl Base URL of the package registry
	RegistryBaseUrl *string `json:"registryBaseUrl,omitempty"`

	// RegistryType Registry type indicating how to download packages (e.g., 'npm', 'pypi', 'oci', 'nuget', 'mcpb')
	RegistryType string `json:"registryType"`

	// RuntimeArguments A list of arguments to be passed to the package's runtime command (such as docker or npx). The `runtimeHint` field should be provided when `runtimeArguments` are present.
	RuntimeArguments *[]Argument `json:"runtimeArguments,omitempty"`

	// RuntimeHint A hint to help clients determine the appropriate runtime for the package. This field should be provided when `runtimeArguments` are present.
	RuntimeHint *string `json:"runtimeHint,omitempty"`

	// Transport Transport protocol configuration for the package
	Transport Package_Transport `json:"transport"`

	// Version Package version. Must be a specific version. Version ranges are rejected (e.g., '^1.2.3', '~1.2.3', '>=1.2.3', '1.x', '1.*').
	Version *string `json:"version,omitempty"`
}

// Package_Transport Transport protocol configuration for the package
type Package_Transport struct {
	union json.RawMessage
}

// PositionalArgument defines model for PositionalArgument.
type PositionalArgument struct {
	// Choices A list of possible values for the input. If provided, the user must select one of these values.
	Choices *[]string `json:"choices,omitempty"`

	// Default The default value for the input.  This should be a valid value for the input.  If you want to provide input examples or guidance, use the `placeholder` field instead.
	Default *string `json:"default,omitempty"`

	// Description A description of the input, which clients can use to provide context to the user.
	Description *string `json:"description,omitempty"`

	// Format Specifies the input format. Supported values include `filepath`, which should be interpreted as a file on the user's filesystem.
	//
	// When the input is converted to a string, booleans should be represented by the strings "true" and "false", and numbers should be represented as decimal values.
	Format *PositionalArgumentFormat `json:"format,omitempty"`

	// IsRepeated Whether the argument can be repeated multiple times in the command line.
	IsRepeated *bool `json:"isRepeated,omitempty"`
	IsRequired *bool `json:"isRequired,omitempty"`

	// IsSecret Indicates whether the input is a secret value (e.g., password, token). If true, clients should handle the value securely.
	IsSecret *bool `json:"isSecret,omitempty"`

	// Placeholder A placeholder for the input to be displaying during configuration. This is used to provide examples or guidance about the expected form or content of the input.
	Placeholder *string                `json:"placeholder,omitempty"`
	Type        PositionalArgumentType `json:"type"`

	// Value The value for the input. If this is not set, the user may be prompted to provide a value. If a value is set, it should not be configurable by end users.
	//
	// Identifiers wrapped in `{curly_braces}` will be replaced with the corresponding properties from the input `variables` map. If an identifier in braces is not found in `variables`, or if `variables` is not provided, the `{curly_braces}` substring should remain unchanged.
	Value *string `json:"value,omitempty"`

	// ValueHint An identifier for the positional argument. It is not part of the command line. It may be used by client configuration as a label identifying the argument. It is also used to identify the value in transport URL variable substitution.
	ValueHint *string `json:"valueHint,omitempty"`

	// Variables A map of variable names to their values. Keys in the input `value` that are wrapped in `{curly_braces}` will be replaced with the corresponding variable values.
	Variables *map[string]Input `json:"variables,omitempty"`
}

// PositionalArgumentFormat Specifies the input format. Supported values include `filepath`, which should be interpreted as a file on the user's filesystem.
//
// When the input is converted to a string, booleans should be represented by the strings "true" and "false", and numbers should be represented as decimal values.
type PositionalArgumentFormat string

// PositionalArgumentType defines model for PositionalArgument.Type.
type PositionalArgumentType string

// Repository Repository metadata for the MCP server source code. Enables users and security experts to inspect the code, improving transparency.
type Repository struct {
	// Id Repository identifier from the hosting service (e.g., GitHub repo ID). Owned and determined by the source forge. Should remain stable across repository renames and may be used to detect repository resurrection attacks - if a repository is deleted and recreated, the ID should change. For GitHub, use: gh api repos/<owner>/<repo> --jq '.id'
	Id *string `json:"id,omitempty"`

	// Source Repository hosting service identifier. Used by registries to determine validation and API access methods.
	Source string `json:"source"`

	// Subfolder Optional relative path from repository root to the server location within a monorepo or nested package structure. Must be a clean relative path.
	Subfolder *string `json:"subfolder,omitempty"`

	// Url Repository URL for browsing source code. Should support both web browsing and git clone operations.
	Url string `json:"url"`
}

// ServerDetail Schema for a static representation of an MCP server. Used in various contexts related to discovery, installation, and configuration.
type ServerDetail struct {
	// Schema JSON Schema URI for this server.json format
	Schema *string `json:"$schema,omitempty"`

	// UnderscoreMeta Extension metadata using reverse DNS namespacing for vendor-specific data
	UnderscoreMeta *struct {
		// IoModelcontextprotocolRegistrypublisherProvided Publisher-provided metadata for downstream registries
		IoModelcontextprotocolRegistrypublisherProvided *map[string]interface{} `json:"io.modelcontextprotocol.registry/publisher-provided,omitempty"`
	} `json:"_meta,omitempty"`

	// Description Clear human-readable explanation of server functionality. Should focus on capabilities, not implementation details.
	Description string `json:"description"`

	// Icons Optional set of sized icons that the client can display in a user interface. Clients that support rendering icons MUST support at least the following MIME types: image/png and image/jpeg (safe, universal compatibility). Clients SHOULD also support: image/svg+xml (scalable but requires security precautions) and image/webp (modern, efficient format).
	Icons *[]Icon `json:"icons,omitempty"`

	// Name Server name in reverse-DNS format. Must contain exactly one forward slash separating namespace from server name.
	Name     string                       `json:"name"`
	Packages *[]Package                   `json:"packages,omitempty"`
	Remotes  *[]ServerDetail_Remotes_Item `json:"remotes,omitempty"`

	// Repository Repository metadata for the MCP server source code. Enables users and security experts to inspect the code, improving transparency.
	Repository *Repository `json:"repository,omitempty"`

	// Title Optional human-readable title or display name for the MCP server. MCP subregistries or clients MAY choose to use this for display purposes.
	Title *string `json:"title,omitempty"`

	// Version Version string for this server. SHOULD follow semantic versioning (e.g., '1.0.2', '2.1.0-alpha'). Equivalent of Implementation.version in MCP specification. Non-semantic versions are allowed but may not sort predictably. Version ranges are rejected (e.g., '^1.2.3', '~1.2.3', '>=1.2.3', '1.x', '1.*').
	Version string `json:"version"`

	// WebsiteUrl Optional URL to the server's homepage, documentation, or project website. This provides a central link for users to learn more about the server. Particularly useful when the server has custom installation instructions or setup requirements.
	WebsiteUrl *string `json:"websiteUrl,omitempty"`
}

// ServerDetail_Remotes_Item defines model for ServerDetail.remotes.Item.
type ServerDetail_Remotes_Item struct {
	union json.RawMessage
}

// ServerList defines model for ServerList.
type ServerList struct {
	Metadata *struct {
		// Count Number of items in current page
		Count *int `json:"count,omitempty"`

		// NextCursor Pagination cursor for retrieving the next page of results.
		// Use this exact value in the `cursor` query parameter of your next request. If null or empty, there are no more results.
		NextCursor *string `json:"nextCursor,omitempty"`
	} `json:"metadata,omitempty"`
	Servers []ServerResponse `json:"servers"`
}

// ServerResponse API response format with separated server data and registry metadata
type ServerResponse struct {
	// UnderscoreMeta Registry-managed metadata
	UnderscoreMeta ServerResponse_Meta `json:"_meta"`

	// Server Schema for a static representation of an MCP server. Used in various contexts related to discovery, installation, and configuration.
	Server ServerDetail `json:"server"`
}

// ServerResponseMetaIoModelcontextprotocolRegistryofficialStatus Server lifecycle status
type ServerResponseMetaIoModelcontextprotocolRegistryofficialStatus string

// ServerResponse_Meta Registry-managed metadata
type ServerResponse_Meta struct {
	// IoModelcontextprotocolRegistryofficial Official MCP registry metadata
	IoModelcontextprotocolRegistryofficial *struct {
		// IsLatest Whether this is the latest version of the server
		IsLatest *bool `json:"isLatest,omitempty"`

		// PublishedAt Timestamp when the server was first published to the registry
		PublishedAt *time.Time `json:"publishedAt,omitempty"`

		// Status Server lifecycle status
		Status *ServerResponseMetaIoModelcontextprotocolRegistryofficialStatus `json:"status,omitempty"`

		// UpdatedAt Timestamp when the server entry was last updated
		UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	} `json:"io.modelcontextprotocol.registry/official,omitempty"`
	AdditionalProperties map[string]interface{} `json:"-"`
}

// SseTransport defines model for SseTransport.
type SseTransport struct {
	// Headers HTTP headers to include
	Headers *[]KeyValueInput `json:"headers,omitempty"`

	// Type Transport type
	Type SseTransportType `json:"type"`

	// Url Server-Sent Events endpoint URL
	Url string `json:"url"`
}

// SseTransportType Transport type
type SseTransportType string

// StdioTransport defines model for StdioTransport.
type StdioTransport struct {
	// Type Transport type
	Type StdioTransportType `json:"type"`
}

// StdioTransportType Transport type
type StdioTransportType string

// StreamableHttpTransport defines model for StreamableHttpTransport.
type StreamableHttpTransport struct {
	// Headers HTTP headers to include
	Headers *[]KeyValueInput `json:"headers,omitempty"`

	// Type Transport type
	Type StreamableHttpTransportType `json:"type"`

	// Url URL template for the streamable-http transport. Variables in {curly_braces} reference argument valueHints, argument names, or environment variable names. After variable substitution, this should produce a valid URI.
	Url string `json:"url"`
}

// StreamableHttpTransportType Transport type
type StreamableHttpTransportType string

// GetV0ServersParams defines parameters for GetV0Servers.
type GetV0ServersParams struct {
	// Cursor Pagination cursor for retrieving next set of results.
	//
	// Cursors are opaque strings returned in the `metadata.nextCursor` field of paginated responses. Always use the exact cursor value returned by the API.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// Limit Maximum number of items to return
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Search Search servers by name (substring match)
	Search *string `form:"search,omitempty" json:"search,omitempty"`

	// UpdatedSince Filter servers updated since timestamp (RFC3339 datetime)
	UpdatedSince *time.Time `form:"updated_since,omitempty" json:"updated_since,omitempty"`

	// Version Filter by version ('latest' for latest version, or an exact version like '1.2.3')
	Version *string `form:"version,omitempty" json:"version,omitempty"`
}

// PostV0PublishJSONRequestBody defines body for PostV0Publish for application/json ContentType.
type PostV0PublishJSONRequestBody = ServerDetail

// Getter for additional properties for ServerResponse_Meta. Returns the specified
// element and whether it was found
func (a ServerResponse_Meta) Get(fieldName string) (value interface{}, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Setter for additional properties for ServerResponse_Meta
func (a *ServerResponse_Meta) Set(fieldName string, value interface{}) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]interface{})
	}
	a.AdditionalProperties[fieldName] = value
}

// Override default JSON handling for ServerResponse_Meta to handle AdditionalProperties
func (a *ServerResponse_Meta) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["io.modelcontextprotocol.registry/official"]; found {
		err = json.Unmarshal(raw, &a.IoModelcontextprotocolRegistryofficial)
		if err != nil {
			return fmt.Errorf("error reading 'io.modelcontextprotocol.registry/official': %w", err)
		}
		delete(object, "io.modelcontextprotocol.registry/official")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]interface{})
		for fieldName, fieldBuf := range object {
			var fieldVal interface{}
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

// Override default JSON handling for ServerResponse_Meta to handle AdditionalProperties
func (a ServerResponse_Meta) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.IoModelcontextprotocolRegistryofficial != nil {
		object["io.modelcontextprotocol.registry/official"], err = json.Marshal(a.IoModelcontextprotocolRegistryofficial)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'io.modelcontextprotocol.registry/official': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// AsPositionalArgument returns the union data inside the Argument as a PositionalArgument
func (t Argument) AsPositionalArgument() (PositionalArgument, error) {
	var body PositionalArgument
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPositionalArgument overwrites any union data inside the Argument as the provided PositionalArgument
func (t *Argument) FromPositionalArgument(v PositionalArgument) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePositionalArgument performs a merge with any union data inside the Argument, using the provided PositionalArgument
func (t *Argument) MergePositionalArgument(v PositionalArgument) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsNamedArgument returns the union data inside the Argument as a NamedArgument
func (t Argument) AsNamedArgument() (NamedArgument, error) {
	var body NamedArgument
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromNamedArgument overwrites any union data inside the Argument as the provided NamedArgument
func (t *Argument) FromNamedArgument(v NamedArgument) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeNamedArgument performs a merge with any union data inside the Argument, using the provided NamedArgument
func (t *Argument) MergeNamedArgument(v NamedArgument) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Argument) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Argument) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsStdioTransport returns the union data inside the Package_Transport as a StdioTransport
func (t Package_Transport) AsStdioTransport() (StdioTransport, error) {
	var body StdioTransport
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStdioTransport overwrites any union data inside the Package_Transport as the provided StdioTransport
func (t *Package_Transport) FromStdioTransport(v StdioTransport) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStdioTransport performs a merge with any union data inside the Package_Transport, using the provided StdioTransport
func (t *Package_Transport) MergeStdioTransport(v StdioTransport) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsStreamableHttpTransport returns the union data inside the Package_Transport as a StreamableHttpTransport
func (t Package_Transport) AsStreamableHttpTransport() (StreamableHttpTransport, error) {
	var body StreamableHttpTransport
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStreamableHttpTransport overwrites any union data inside the Package_Transport as the provided StreamableHttpTransport
func (t *Package_Transport) FromStreamableHttpTransport(v StreamableHttpTransport) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStreamableHttpTransport performs a merge with any union data inside the Package_Transport, using the provided StreamableHttpTransport
func (t *Package_Transport) MergeStreamableHttpTransport(v StreamableHttpTransport) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSseTransport returns the union data inside the Package_Transport as a SseTransport
func (t Package_Transport) AsSseTransport() (SseTransport, error) {
	var body SseTransport
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSseTransport overwrites any union data inside the Package_Transport as the provided SseTransport
func (t *Package_Transport) FromSseTransport(v SseTransport) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSseTransport performs a merge with any union data inside the Package_Transport, using the provided SseTransport
func (t *Package_Transport) MergeSseTransport(v SseTransport) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Package_Transport) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Package_Transport) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsStreamableHttpTransport returns the union data inside the ServerDetail_Remotes_Item as a StreamableHttpTransport
func (t ServerDetail_Remotes_Item) AsStreamableHttpTransport() (StreamableHttpTransport, error) {
	var body StreamableHttpTransport
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromStreamableHttpTransport overwrites any union data inside the ServerDetail_Remotes_Item as the provided StreamableHttpTransport
func (t *ServerDetail_Remotes_Item) FromStreamableHttpTransport(v StreamableHttpTransport) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeStreamableHttpTransport performs a merge with any union data inside the ServerDetail_Remotes_Item, using the provided StreamableHttpTransport
func (t *ServerDetail_Remotes_Item) MergeStreamableHttpTransport(v StreamableHttpTransport) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsSseTransport returns the union data inside the ServerDetail_Remotes_Item as a SseTransport
func (t ServerDetail_Remotes_Item) AsSseTransport() (SseTransport, error) {
	var body SseTransport
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromSseTransport overwrites any union data inside the ServerDetail_Remotes_Item as the provided SseTransport
func (t *ServerDetail_Remotes_Item) FromSseTransport(v SseTransport) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeSseTransport performs a merge with any union data inside the ServerDetail_Remotes_Item, using the provided SseTransport
func (t *ServerDetail_Remotes_Item) MergeSseTransport(v SseTransport) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ServerDetail_Remotes_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ServerDetail_Remotes_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
