// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	InsertRegistry(ctx context.Context, arg InsertRegistryParams) error
}

var _ Querier = (*Queries)(nil)
