// Code generated by MockGen. DO NOT EDIT.
// Source: factory.go
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_factory.go -package=mocks -source=factory.go Factory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/stacklok/toolhive-registry-server/internal/service"
	state "github.com/stacklok/toolhive-registry-server/internal/sync/state"
	writer "github.com/stacklok/toolhive-registry-server/internal/sync/writer"
	gomock "go.uber.org/mock/gomock"
)

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// Cleanup mocks base method.
func (m *MockFactory) Cleanup() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cleanup")
}

// Cleanup indicates an expected call of Cleanup.
func (mr *MockFactoryMockRecorder) Cleanup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleanup", reflect.TypeOf((*MockFactory)(nil).Cleanup))
}

// CreateRegistryService mocks base method.
func (m *MockFactory) CreateRegistryService(ctx context.Context) (service.RegistryService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRegistryService", ctx)
	ret0, _ := ret[0].(service.RegistryService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRegistryService indicates an expected call of CreateRegistryService.
func (mr *MockFactoryMockRecorder) CreateRegistryService(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRegistryService", reflect.TypeOf((*MockFactory)(nil).CreateRegistryService), ctx)
}

// CreateStateService mocks base method.
func (m *MockFactory) CreateStateService(ctx context.Context) (state.RegistryStateService, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStateService", ctx)
	ret0, _ := ret[0].(state.RegistryStateService)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStateService indicates an expected call of CreateStateService.
func (mr *MockFactoryMockRecorder) CreateStateService(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStateService", reflect.TypeOf((*MockFactory)(nil).CreateStateService), ctx)
}

// CreateSyncWriter mocks base method.
func (m *MockFactory) CreateSyncWriter(ctx context.Context) (writer.SyncWriter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSyncWriter", ctx)
	ret0, _ := ret[0].(writer.SyncWriter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSyncWriter indicates an expected call of CreateSyncWriter.
func (mr *MockFactoryMockRecorder) CreateSyncWriter(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSyncWriter", reflect.TypeOf((*MockFactory)(nil).CreateSyncWriter), ctx)
}
